// Roamio — Master Destination Database
// Combines all 5 parts: ~108 destinations total
//
// Structure per destination:
// {
//   id, name, state_country, international, visa_required, region,
//   proximity_hours: { Delhi, Mumbai, Bangalore, Chennai, Hyderabad, Kolkata, Pune, Ahmedabad },
//   experience_types: [],   // mountains, beach, nature, culture, heritage, food, adventure, chill,
//                           //   nightlife, spiritual, pilgrimage, offbeat, wildlife, city, luxury, shopping
//   group_fit: [],          // couple, friends, family-kids, solo
//   budget: { tiers: [], min_per_day, max_per_day },
//                           // tiers: tight (<₹1.5k), budget (₹1.5–3.5k), mid (₹3.5–8k), premium (₹8k+)
//   duration: { min_days, ideal_days, max_days },
//   best_months: [],        // 1–12
//   avoid_months: [],       // 1–12
//   scores: {               // 1–5 per dimension
//     romance, adventure, culture, party, nature,
//     family_friendly, spiritual, offbeat, food, safety, solo_friendly
//   },
//   tags: [],
//   why_go: "",
//   not_for: [],
//   budget_note: ""
// }

// ─── PART 1: NORTH INDIA (28 destinations) ──────────────────────────────────
const destinations_part1 = [
  {
    id: "manali",
    name: "Manali",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 14, Mumbai: 36, Bangalore: 48, Chennai: 50, Hyderabad: 44, Kolkata: 42, Pune: 38, Ahmedabad: 32 },
    experience_types: ["mountains", "adventure", "nature", "chill"],
    group_fit: ["couple", "friends", "solo", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 8000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 8 },
    best_months: [4, 5, 6, 10, 11],
    avoid_months: [12, 1, 2],
    scores: { romance: 4, adventure: 5, culture: 2, party: 2, nature: 5, family_friendly: 3, spiritual: 2, offbeat: 2, food: 3, safety: 4, solo_friendly: 4 },
    tags: ["Rohtang Pass", "Solang Valley", "river rafting", "paragliding", "snow", "Old Manali cafes", "Hadimba Temple", "Beas River"],
    why_go: "The most popular mountain escape from North India — stunning snow-capped peaks, adventure sports, and a laid-back old town vibe with riverside cafes.",
    not_for: ["beach lovers", "party groups"],
    budget_note: "₹2000–8000/person/day"
  },
  {
    id: "shimla_kufri",
    name: "Shimla + Kufri",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 10, Mumbai: 34, Bangalore: 46, Chennai: 48, Hyderabad: 42, Kolkata: 38, Pune: 36, Ahmedabad: 30 },
    experience_types: ["mountains", "heritage", "nature", "chill"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 2, ideal_days: 4, max_days: 5 },
    best_months: [3, 4, 5, 10, 11, 12],
    avoid_months: [],
    scores: { romance: 4, adventure: 2, culture: 3, party: 1, nature: 4, family_friendly: 5, spiritual: 2, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Mall Road", "Christ Church", "toy train", "Kufri snow", "colonial architecture", "apple orchards", "Jakhu Temple"],
    why_go: "The classic family hill station — British colonial charm, a beloved toy train, Kufri for snow, and gentle walks. India's most recognizable mountain destination.",
    not_for: ["adventure seekers", "party groups", "offbeat travelers"],
    budget_note: "₹2000–7000/person/day"
  },
  {
    id: "kasol_kheerganga",
    name: "Kasol + Kheerganga",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 12, Mumbai: 36, Bangalore: 50, Chennai: 52, Hyderabad: 46, Kolkata: 44, Pune: 38, Ahmedabad: 34 },
    experience_types: ["mountains", "nature", "offbeat", "adventure", "chill"],
    group_fit: ["friends", "solo", "couple"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 5000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 7 },
    best_months: [4, 5, 6, 9, 10],
    avoid_months: [12, 1, 2, 3],
    scores: { romance: 3, adventure: 4, culture: 2, party: 2, nature: 5, family_friendly: 1, spiritual: 2, offbeat: 5, food: 3, safety: 3, solo_friendly: 5 },
    tags: ["Parvati Valley", "Kheerganga trek", "hot springs", "Israel vibe", "backpacker cafes", "Chalal trek", "camping", "river side"],
    why_go: "India's most beloved backpacker valley — Israeli cafes, riverside camping, the rewarding Kheerganga hot spring trek, and a distinct countercultural energy.",
    not_for: ["families with kids", "luxury travelers", "senior travelers"],
    budget_note: "₹1500–5000/person/day. One of India's cheapest mountain destinations."
  },
  {
    id: "mcleod_ganj",
    name: "McLeod Ganj (Dharamshala)",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 12, Mumbai: 36, Bangalore: 50, Chennai: 52, Hyderabad: 46, Kolkata: 44, Pune: 38, Ahmedabad: 34 },
    experience_types: ["spiritual", "culture", "mountains", "offbeat", "chill"],
    group_fit: ["solo", "couple", "friends"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 5000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 7 },
    best_months: [3, 4, 5, 9, 10, 11],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 3, culture: 4, party: 1, nature: 4, family_friendly: 3, spiritual: 5, offbeat: 4, food: 4, safety: 5, solo_friendly: 5 },
    tags: ["Dalai Lama temple", "Tibetan culture", "momos", "Triund trek", "meditation", "Bhagsu waterfall", "monasteries", "Little Lhasa"],
    why_go: "Home of the Dalai Lama and Tibetan government-in-exile — a unique spiritual town with excellent trekking, outstanding Tibetan food, and a deeply peaceful atmosphere.",
    not_for: ["party groups", "beach lovers"],
    budget_note: "₹1500–5000/person/day"
  },
  {
    id: "spiti_valley",
    name: "Spiti Valley",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 18, Mumbai: 42, Bangalore: 56, Chennai: 58, Hyderabad: 52, Kolkata: 50, Pune: 44, Ahmedabad: 40 },
    experience_types: ["mountains", "adventure", "offbeat", "spiritual", "nature"],
    group_fit: ["friends", "solo", "couple"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 6000 },
    duration: { min_days: 5, ideal_days: 8, max_days: 12 },
    best_months: [6, 7, 8, 9],
    avoid_months: [10, 11, 12, 1, 2, 3, 4, 5],
    scores: { romance: 3, adventure: 5, culture: 3, party: 1, nature: 5, family_friendly: 1, spiritual: 5, offbeat: 5, food: 2, safety: 3, solo_friendly: 4 },
    tags: ["Key Monastery", "Chandratal Lake", "Pin Valley", "stargazing", "high altitude desert", "remote villages", "fossil hunting", "Kunzum Pass"],
    why_go: "India's most dramatic high-altitude desert valley — stark lunar landscapes, ancient monasteries, sub-zero camping, and some of the best stargazing in Asia.",
    not_for: ["families with kids", "luxury travelers", "those prone to altitude sickness", "short trips"],
    budget_note: "₹2000–6000/person/day. Roads open only June–September."
  },
  {
    id: "bir_billing",
    name: "Bir Billing",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 13, Mumbai: 37, Bangalore: 51, Chennai: 53, Hyderabad: 47, Kolkata: 45, Pune: 39, Ahmedabad: 35 },
    experience_types: ["adventure", "mountains", "offbeat", "spiritual"],
    group_fit: ["friends", "solo", "couple"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 4, max_days: 5 },
    best_months: [3, 4, 5, 9, 10, 11],
    avoid_months: [12, 1, 2, 6, 7, 8],
    scores: { romance: 3, adventure: 5, culture: 2, party: 1, nature: 5, family_friendly: 2, spiritual: 3, offbeat: 4, food: 3, safety: 4, solo_friendly: 4 },
    tags: ["paragliding world cup site", "landing site", "Tibetan colony", "tea gardens", "hiking", "camping"],
    why_go: "The paragliding capital of India and Asia — world-record flights from Billing with a 2500m drop to Bir's Tibetan colony. Also an up-and-coming peaceful retreat.",
    not_for: ["beach lovers", "party groups", "families with young kids"],
    budget_note: "₹2000–6000/person/day. Paragliding ₹2500–4000/flight."
  },
  {
    id: "chitkul",
    name: "Chitkul",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 15, Mumbai: 40, Bangalore: 54, Chennai: 56, Hyderabad: 50, Kolkata: 48, Pune: 42, Ahmedabad: 38 },
    experience_types: ["mountains", "offbeat", "nature", "chill"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 5000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [6, 7, 8, 9],
    avoid_months: [10, 11, 12, 1, 2, 3, 4, 5],
    scores: { romance: 4, adventure: 3, culture: 2, party: 1, nature: 5, family_friendly: 2, spiritual: 2, offbeat: 5, food: 2, safety: 4, solo_friendly: 4 },
    tags: ["last village", "Indo-Tibetan border", "Baspa River", "apple trees", "wooden homes", "pristine", "Kinnaur"],
    why_go: "India's last inhabited village before the Tibet border — jaw-dropping Himalayan scenery with apple orchards, ancient wooden homes, and a truly remote, unspoiled atmosphere.",
    not_for: ["families with kids", "luxury travelers", "rainy season trips"],
    budget_note: "₹1500–5000/person/day. Best combined with Sangla Valley."
  },
  {
    id: "harsil",
    name: "Harsil",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 11, Mumbai: 36, Bangalore: 50, Chennai: 52, Hyderabad: 46, Kolkata: 44, Pune: 38, Ahmedabad: 34 },
    experience_types: ["mountains", "nature", "offbeat", "chill", "spiritual"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 5000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [4, 5, 6, 9, 10],
    avoid_months: [12, 1, 2, 7, 8],
    scores: { romance: 5, adventure: 3, culture: 2, party: 1, nature: 5, family_friendly: 3, spiritual: 3, offbeat: 5, food: 2, safety: 4, solo_friendly: 4 },
    tags: ["Bhagirathi River", "apple orchards", "Sattal", "Gangotri nearby", "deodar forest", "Uttarkashi", "offbeat Uttarakhand"],
    why_go: "One of Uttarakhand's best-kept secrets — a quiet valley of apple orchards and deodar forests along the crystal-clear Bhagirathi, en route to Gangotri. Perfect for couples escaping the crowd.",
    not_for: ["party groups", "luxury travelers", "beach lovers"],
    budget_note: "₹1500–5000/person/day"
  },
  {
    id: "rishikesh",
    name: "Rishikesh",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 6, Mumbai: 28, Bangalore: 42, Chennai: 44, Hyderabad: 38, Kolkata: 36, Pune: 30, Ahmedabad: 26 },
    experience_types: ["adventure", "spiritual", "yoga", "nature"],
    group_fit: ["friends", "solo", "couple", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 4, max_days: 7 },
    best_months: [2, 3, 4, 9, 10, 11],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 5, culture: 3, party: 1, nature: 4, family_friendly: 3, spiritual: 5, offbeat: 2, food: 3, safety: 4, solo_friendly: 5 },
    tags: ["white water rafting", "bungee jumping", "Beatles Ashram", "Ganga aarti", "yoga capital", "Laxman Jhula", "camping", "cliff jumping"],
    why_go: "India's adventure and yoga capital — world-class white-water rafting, bungee jumping, and a spiritual pulse on the banks of the Ganga. Perfect for groups mixing adventure with calm.",
    not_for: ["luxury travelers", "party groups"],
    budget_note: "₹1500–6000/person/day. Adventure packages ₹1500–3000 add-on."
  },
  {
    id: "haridwar",
    name: "Haridwar",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 5, Mumbai: 27, Bangalore: 41, Chennai: 43, Hyderabad: 37, Kolkata: 35, Pune: 29, Ahmedabad: 25 },
    experience_types: ["spiritual", "pilgrimage", "culture"],
    group_fit: ["family-kids", "couple", "solo"],
    budget: { tiers: ["tight", "budget"], min_per_day: 1000, max_per_day: 4000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [2, 3, 10, 11, 12],
    avoid_months: [6, 7, 8],
    scores: { romance: 2, adventure: 1, culture: 4, party: 1, nature: 3, family_friendly: 5, spiritual: 5, offbeat: 1, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["Ganga Aarti", "Har Ki Pauri", "Kumbh Mela", "ghats", "pilgrimage", "temples", "prasad"],
    why_go: "One of Hinduism's holiest cities — the Ganga Aarti at Har Ki Pauri at dusk is a profoundly moving experience. Often combined with Rishikesh.",
    not_for: ["adventure seekers", "party groups", "beach lovers"],
    budget_note: "₹1000–4000/person/day. Very affordable pilgrimage destination."
  },
  {
    id: "mussoorie",
    name: "Mussoorie",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 7, Mumbai: 29, Bangalore: 43, Chennai: 45, Hyderabad: 39, Kolkata: 37, Pune: 31, Ahmedabad: 27 },
    experience_types: ["mountains", "chill", "nature"],
    group_fit: ["couple", "family-kids", "friends"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [3, 4, 5, 10, 11, 12],
    avoid_months: [],
    scores: { romance: 4, adventure: 2, culture: 2, party: 1, nature: 4, family_friendly: 5, spiritual: 1, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Mall Road", "Kempty Falls", "Gun Hill", "Lal Tibba", "Camel's Back Road", "colonial feel", "Landour bakery"],
    why_go: "The Queen of Hills — a charming colonial hill station with mountain views, lovely promenade walks, and a distinctly British-era feel. Classic family weekend escape from Delhi.",
    not_for: ["adventure seekers", "offbeat travelers"],
    budget_note: "₹2000–7000/person/day"
  },
  {
    id: "nainital",
    name: "Nainital",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 7, Mumbai: 30, Bangalore: 44, Chennai: 46, Hyderabad: 40, Kolkata: 36, Pune: 32, Ahmedabad: 28 },
    experience_types: ["nature", "mountains", "chill", "family"],
    group_fit: ["family-kids", "couple", "friends"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [3, 4, 5, 10, 11],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 2, culture: 2, party: 1, nature: 4, family_friendly: 5, spiritual: 2, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Naini Lake", "boating", "Mall Road", "Naina Devi Temple", "Tiffin Top", "Snow View", "Corbett nearby"],
    why_go: "Uttarakhand's most beloved lake town — gentle boat rides on Naini Lake, panoramic snow views, and a laid-back mall road. Great for families and couples.",
    not_for: ["adventure seekers", "offbeat travelers", "party groups"],
    budget_note: "₹2000–6000/person/day"
  },
  {
    id: "chopta_tungnath",
    name: "Chopta + Tungnath",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 10, Mumbai: 34, Bangalore: 48, Chennai: 50, Hyderabad: 44, Kolkata: 42, Pune: 36, Ahmedabad: 32 },
    experience_types: ["mountains", "spiritual", "adventure", "offbeat", "nature"],
    group_fit: ["friends", "solo", "couple"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 5000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [4, 5, 6, 10, 11],
    avoid_months: [12, 1, 2, 7, 8],
    scores: { romance: 4, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 2, spiritual: 5, offbeat: 5, food: 2, safety: 4, solo_friendly: 4 },
    tags: ["Tungnath temple", "world's highest Shiva temple", "Chandrashila peak", "rhododendron forest", "Deoriatal", "bugyal meadows"],
    why_go: "Uttarakhand's mini Switzerland — rolling meadows of rhododendrons, the world's highest Shiva temple, and a relatively easy trek to Chandrashila peak for 360° Himalayan views.",
    not_for: ["luxury travelers", "families with very young kids"],
    budget_note: "₹1500–5000/person/day. Himalayan gem without Kedarnath crowds."
  },
  {
    id: "kedarkantha",
    name: "Kedarkantha Trek",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 10, Mumbai: 34, Bangalore: 48, Chennai: 50, Hyderabad: 44, Kolkata: 42, Pune: 36, Ahmedabad: 32 },
    experience_types: ["adventure", "mountains", "nature", "trekking"],
    group_fit: ["friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 6000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 7 },
    best_months: [12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 2, adventure: 5, culture: 1, party: 1, nature: 5, family_friendly: 1, spiritual: 2, offbeat: 4, food: 2, safety: 4, solo_friendly: 5 },
    tags: ["summit trek", "snow camping", "Sankri", "pine forests", "winter trek", "beginner friendly", "Govind Wildlife Sanctuary"],
    why_go: "India's best beginner winter trek — snow-covered pine forests, high-altitude camping, and a stunning 12,500ft summit with 360° views of the Greater Himalayas.",
    not_for: ["families with kids", "luxury travelers", "non-trekkers"],
    budget_note: "₹2000–6000/person/day. Trek packages ₹8000–15000 for 6 days."
  },
  {
    id: "valley_of_flowers",
    name: "Valley of Flowers",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 12, Mumbai: 36, Bangalore: 50, Chennai: 52, Hyderabad: 46, Kolkata: 44, Pune: 38, Ahmedabad: 34 },
    experience_types: ["nature", "trekking", "spiritual", "offbeat"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 6000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 7 },
    best_months: [7, 8, 9],
    avoid_months: [10, 11, 12, 1, 2, 3, 4, 5, 6],
    scores: { romance: 4, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 2, spiritual: 4, offbeat: 5, food: 2, safety: 4, solo_friendly: 4 },
    tags: ["UNESCO", "Hemkund Sahib", "alpine flowers", "glaciers", "Pushpawati River", "Nanda Devi National Park", "rare orchids"],
    why_go: "A UNESCO World Heritage site — in July–September, this entire valley erupts in 300+ species of wildflowers. One of India's most unique natural spectacles.",
    not_for: ["luxury travelers", "non-trekkers", "families with young kids"],
    budget_note: "₹2000–6000/person/day. Trek packages ₹10000–18000. Open July–October only."
  },
  {
    id: "mukteshwar",
    name: "Mukteshwar",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 8, Mumbai: 32, Bangalore: 46, Chennai: 48, Hyderabad: 42, Kolkata: 40, Pune: 34, Ahmedabad: 30 },
    experience_types: ["mountains", "chill", "nature", "offbeat"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [3, 4, 5, 10, 11, 12],
    avoid_months: [6, 7, 8],
    scores: { romance: 5, adventure: 3, culture: 2, party: 1, nature: 5, family_friendly: 3, spiritual: 3, offbeat: 4, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["Chauli Ki Jali cliff", "Himalayan views", "apple orchards", "peaceful", "rock climbing", "sunset point", "IVRI campus"],
    why_go: "Nainital's quieter, more scenic neighbor — the Chauli Ki Jali ledge offers some of the best unobstructed Himalayan views in the Kumaon, with far fewer crowds.",
    not_for: ["party groups", "luxury travelers"],
    budget_note: "₹2000–7000/person/day"
  },
  {
    id: "jim_corbett",
    name: "Jim Corbett National Park",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 6, Mumbai: 28, Bangalore: 42, Chennai: 44, Hyderabad: 38, Kolkata: 34, Pune: 30, Ahmedabad: 26 },
    experience_types: ["wildlife", "nature", "adventure"],
    group_fit: ["family-kids", "couple", "friends"],
    budget: { tiers: ["mid", "premium"], min_per_day: 4000, max_per_day: 15000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [11, 12, 1, 2, 3, 4, 5, 6],
    avoid_months: [7, 8, 9, 10],
    scores: { romance: 3, adventure: 4, culture: 1, party: 1, nature: 5, family_friendly: 5, spiritual: 1, offbeat: 2, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["tiger safari", "elephant ride", "Dhikala zone", "leopard", "jeep safari", "Ramganga River", "bird watching", "India's oldest national park"],
    why_go: "India's oldest and most celebrated tiger reserve — excellent tiger sighting probability in Dhikala zone, great elephant and leopard sightings, and an immersive jungle lodge experience.",
    not_for: ["party groups", "beach lovers", "city crowd"],
    budget_note: "₹4000–15000/person/day. Safari permits ₹3000–5000 extra."
  },
  {
    id: "auli",
    name: "Auli",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 12, Mumbai: 36, Bangalore: 50, Chennai: 52, Hyderabad: 46, Kolkata: 44, Pune: 38, Ahmedabad: 34 },
    experience_types: ["adventure", "mountains", "nature", "skiing"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 10000 },
    duration: { min_days: 2, ideal_days: 4, max_days: 5 },
    best_months: [1, 2, 3, 5, 6, 10, 11],
    avoid_months: [7, 8, 9],
    scores: { romance: 4, adventure: 5, culture: 1, party: 1, nature: 5, family_friendly: 3, spiritual: 3, offbeat: 3, food: 2, safety: 4, solo_friendly: 4 },
    tags: ["skiing", "cable car", "Nanda Devi views", "Joshimath", "bugyal meadows", "Gurso Bugyal trek", "snow slopes"],
    why_go: "India's best skiing destination — with the Nanda Devi and Kamet peaks as backdrop, and a cable car that offers some of the most dramatic Himalayan panoramas anywhere.",
    not_for: ["beach lovers", "luxury travelers who want comfort"],
    budget_note: "₹3000–10000/person/day. Ski rental ₹1000–2000/day. Jan–March for snow."
  },
  {
    id: "jaipur",
    name: "Jaipur",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 5, Mumbai: 18, Bangalore: 32, Chennai: 34, Hyderabad: 28, Kolkata: 30, Pune: 20, Ahmedabad: 12 },
    experience_types: ["heritage", "culture", "food", "shopping"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 2000, max_per_day: 15000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [4, 5, 6, 7],
    scores: { romance: 4, adventure: 2, culture: 5, party: 2, nature: 2, family_friendly: 5, spiritual: 3, offbeat: 1, food: 5, safety: 4, solo_friendly: 4 },
    tags: ["Hawa Mahal", "Amber Fort", "City Palace", "Jantar Mantar", "Blue Pottery", "laal maas", "dal baati churma", "block printing", "Pink City"],
    why_go: "The Pink City — Rajasthan's royal capital with magnificent forts, vibrant bazaars, and some of North India's best food. An essential India experience.",
    not_for: ["beach lovers", "adventure seekers"],
    budget_note: "₹2000–15000/person/day. Scales from budget guesthouses to palace hotels."
  },
  {
    id: "jodhpur",
    name: "Jodhpur",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 9, Mumbai: 12, Bangalore: 28, Chennai: 32, Hyderabad: 26, Kolkata: 34, Pune: 14, Ahmedabad: 8 },
    experience_types: ["heritage", "culture", "food", "offbeat"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 2000, max_per_day: 15000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [4, 5, 6, 7],
    scores: { romance: 4, adventure: 2, culture: 5, party: 1, nature: 2, family_friendly: 4, spiritual: 3, offbeat: 3, food: 5, safety: 5, solo_friendly: 4 },
    tags: ["Mehrangarh Fort", "Blue City", "Umaid Bhawan", "mirchi bada", "rooftop cafes", "old city lanes", "Jaswant Thada"],
    why_go: "The Blue City — Mehrangarh is India's most impressive fort, the blue-painted old city lanes are Instagram gold, and the rooftop cafe culture is one of India's best.",
    not_for: ["beach lovers", "party groups"],
    budget_note: "₹2000–15000/person/day"
  },
  {
    id: "jaisalmer",
    name: "Jaisalmer",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 13, Mumbai: 16, Bangalore: 32, Chennai: 36, Hyderabad: 30, Kolkata: 38, Pune: 18, Ahmedabad: 12 },
    experience_types: ["heritage", "adventure", "culture", "offbeat"],
    group_fit: ["couple", "friends", "solo", "family-kids"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 2000, max_per_day: 12000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [4, 5, 6, 7, 8, 9],
    scores: { romance: 5, adventure: 4, culture: 4, party: 2, nature: 4, family_friendly: 4, spiritual: 2, offbeat: 4, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["desert camp", "camel safari", "Sam dunes", "Golden Fort", "Patwon Ki Haveli", "stargazing", "Desert Festival", "Thar Desert"],
    why_go: "The Golden City — a living medieval fort rising from the Thar Desert, overnight desert camping under stars, and camel safaris through sand dunes. Pure Rajasthan magic.",
    not_for: ["beach lovers", "those avoiding extreme heat (summer)"],
    budget_note: "₹2000–12000/person/day. Desert camp ₹3000–8000/night."
  },
  {
    id: "udaipur",
    name: "Udaipur",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 12, Mumbai: 8, Bangalore: 24, Chennai: 28, Hyderabad: 22, Kolkata: 36, Pune: 10, Ahmedabad: 6 },
    experience_types: ["heritage", "romance", "culture", "chill"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 20000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [4, 5, 6, 7],
    scores: { romance: 5, adventure: 2, culture: 5, party: 2, nature: 3, family_friendly: 4, spiritual: 3, offbeat: 2, food: 4, safety: 5, solo_friendly: 3 },
    tags: ["City Palace", "Lake Pichola", "boat ride", "Jag Mandir", "rooftop restaurants", "Lake Palace hotel", "Sajjangarh", "Gangaur Festival"],
    why_go: "The most romantic city in India — palaces rising from shimmering lakes, candlelit rooftop dinners with lake views, and a regal atmosphere that feels like stepping into a painting.",
    not_for: ["adventure seekers", "beach lovers"],
    budget_note: "₹3000–20000/person/day. Lake view hotels push costs up significantly."
  },
  {
    id: "pushkar",
    name: "Pushkar",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 8, Mumbai: 16, Bangalore: 30, Chennai: 32, Hyderabad: 26, Kolkata: 34, Pune: 18, Ahmedabad: 12 },
    experience_types: ["spiritual", "culture", "offbeat", "chill"],
    group_fit: ["solo", "couple", "friends"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1000, max_per_day: 5000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [4, 5, 6, 7, 8, 9],
    scores: { romance: 3, adventure: 1, culture: 4, party: 1, nature: 2, family_friendly: 3, spiritual: 5, offbeat: 4, food: 3, safety: 5, solo_friendly: 5 },
    tags: ["Brahma Temple", "Pushkar Lake", "camel fair", "rooftop cafes", "Israeli travelers", "ghats", "rose farming"],
    why_go: "One of India's holiest towns and most unique travel experiences — the world-famous Pushkar Camel Fair, a sacred lake ringed by ghats, and a distinctly hippie-spiritual vibe.",
    not_for: ["party groups", "luxury travelers", "families looking for activities"],
    budget_note: "₹1000–5000/person/day. Very affordable. Best time: Camel Fair (Oct–Nov)."
  },
  {
    id: "ranthambore",
    name: "Ranthambore",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 5, Mumbai: 16, Bangalore: 32, Chennai: 36, Hyderabad: 30, Kolkata: 32, Pune: 18, Ahmedabad: 12 },
    experience_types: ["wildlife", "nature", "heritage"],
    group_fit: ["family-kids", "couple", "friends"],
    budget: { tiers: ["mid", "premium"], min_per_day: 4000, max_per_day: 15000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5, 6],
    avoid_months: [7, 8, 9],
    scores: { romance: 3, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 5, spiritual: 1, offbeat: 2, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["tiger safari", "Ranthambore Fort", "jeep safari", "canter safari", "leopard", "sloth bear", "Rajbagh ruins"],
    why_go: "India's most tiger-friendly reserve — uniquely, tigers are often seen near ancient fort ruins and lakes making for dramatic sightings. One of the best wildlife experiences in India.",
    not_for: ["party groups", "beach lovers", "city crowd"],
    budget_note: "₹4000–15000/person/day. Safari ₹2000–4000 extra."
  },
  {
    id: "agra",
    name: "Agra",
    state_country: "Uttar Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 3, Mumbai: 20, Bangalore: 36, Chennai: 38, Hyderabad: 32, Kolkata: 24, Pune: 22, Ahmedabad: 16 },
    experience_types: ["heritage", "culture"],
    group_fit: ["couple", "family-kids", "friends", "solo"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 2000, max_per_day: 12000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [4, 5, 6, 7, 8, 9],
    scores: { romance: 5, adventure: 1, culture: 5, party: 1, nature: 2, family_friendly: 4, spiritual: 3, offbeat: 1, food: 3, safety: 3, solo_friendly: 4 },
    tags: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "petha", "Mughal history", "sunrise Taj", "Mehtab Bagh"],
    why_go: "Home to the Taj Mahal — one of the world's greatest monuments and every Indian's must-see. The sunrise view from across the Yamuna remains one of travel's defining moments.",
    not_for: ["adventure seekers", "party groups"],
    budget_note: "₹2000–12000/person/day. Taj entry ₹1100 Indians. Often done as Delhi day trip."
  },
  {
    id: "varanasi",
    name: "Varanasi",
    state_country: "Uttar Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 8, Mumbai: 24, Bangalore: 38, Chennai: 36, Hyderabad: 32, Kolkata: 14, Pune: 26, Ahmedabad: 22 },
    experience_types: ["spiritual", "culture", "heritage", "pilgrimage"],
    group_fit: ["family-kids", "couple", "solo", "friends"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1500, max_per_day: 7000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8, 9],
    scores: { romance: 2, adventure: 2, culture: 5, party: 1, nature: 3, family_friendly: 3, spiritual: 5, offbeat: 3, food: 4, safety: 3, solo_friendly: 4 },
    tags: ["Ganga Aarti", "Dashashwamedh Ghat", "boat at sunrise", "Kashi Vishwanath", "silk weaving", "lassi", "Sarnath", "Dev Deepawali"],
    why_go: "India's most ancient living city and the spiritual heart of Hinduism — the Ganga Aarti at Dashashwamedh is genuinely moving, and the maze-like lanes are full of centuries of history.",
    not_for: ["beach lovers", "luxury seekers (infrastructure is basic)", "party groups"],
    budget_note: "₹1500–7000/person/day. One of India's most affordable spiritual destinations."
  },
  {
    id: "mathura_vrindavan",
    name: "Mathura + Vrindavan",
    state_country: "Uttar Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 3, Mumbai: 20, Bangalore: 36, Chennai: 38, Hyderabad: 32, Kolkata: 24, Pune: 22, Ahmedabad: 16 },
    experience_types: ["spiritual", "pilgrimage", "culture"],
    group_fit: ["family-kids", "couple", "solo"],
    budget: { tiers: ["tight", "budget"], min_per_day: 1000, max_per_day: 4000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8, 9],
    scores: { romance: 2, adventure: 1, culture: 3, party: 1, nature: 2, family_friendly: 4, spiritual: 5, offbeat: 1, food: 3, safety: 4, solo_friendly: 3 },
    tags: ["Krishna Janmabhoomi", "ISKCON", "Holi festival", "peda sweets", "Banke Bihari temple", "Vrindavan", "Barsana Holi"],
    why_go: "The birthplace of Lord Krishna — the most important pilgrimage for Vaishnavas. The Holi celebrations here (especially Barsana and Vrindavan) are legendary and unlike anywhere else.",
    not_for: ["adventure seekers", "beach lovers", "luxury travelers"],
    budget_note: "₹1000–4000/person/day. Very affordable pilgrimage."
  },
  {
    id: "gwalior",
    name: "Gwalior",
    state_country: "Madhya Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 4, Mumbai: 16, Bangalore: 32, Chennai: 34, Hyderabad: 28, Kolkata: 22, Pune: 18, Ahmedabad: 14 },
    experience_types: ["heritage", "culture", "offbeat"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [4, 5, 6, 7, 8, 9],
    scores: { romance: 3, adventure: 2, culture: 5, party: 1, nature: 2, family_friendly: 4, spiritual: 3, offbeat: 4, food: 3, safety: 4, solo_friendly: 4 },
    tags: ["Gwalior Fort", "Man Singh Palace", "Jai Vilas Palace", "Tansen festival", "Sas Bahu temples", "classical music heritage", "underrated"],
    why_go: "One of India's most underrated heritage gems — Gwalior Fort is among the finest in the country, with 1000 years of layered history, stunning palaces, and a city that hasn't been overrun by tourists.",
    not_for: ["beach lovers", "adventure seekers"],
    budget_note: "₹1500–6000/person/day. Very affordable as a day trip from Delhi or Agra."
  },
  {
    id: "khajuraho",
    name: "Khajuraho",
    state_country: "Madhya Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 10, Mumbai: 22, Bangalore: 36, Chennai: 38, Hyderabad: 32, Kolkata: 26, Pune: 24, Ahmedabad: 20 },
    experience_types: ["heritage", "culture", "offbeat"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [4, 5, 6, 7, 8, 9],
    scores: { romance: 3, adventure: 1, culture: 5, party: 1, nature: 2, family_friendly: 2, spiritual: 4, offbeat: 4, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["UNESCO temples", "erotic sculptures", "Chandela dynasty", "Western Group", "light and sound show", "Panna Tiger Reserve nearby"],
    why_go: "UNESCO World Heritage temples with extraordinary medieval sculpture — the Chandela temples are masterpieces of Indian art, and the erotic carvings represent a sophisticated understanding of life.",
    not_for: ["families with young children", "beach lovers"],
    budget_note: "₹2000–7000/person/day. Often combined with Orchha for a 3-day Central India circuit."
  }
];

// ─── PART 2: SOUTH INDIA (20 destinations) ──────────────────────────────────
const destinations_part2 = [
  {
    id: "coorg",
    name: "Coorg (Kodagu)",
    state_country: "Karnataka, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 26, Mumbai: 14, Bangalore: 4, Chennai: 6, Hyderabad: 10, Kolkata: 30, Pune: 16, Ahmedabad: 20 },
    experience_types: ["mountains", "nature", "chill", "wildlife"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 2, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 2, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["coffee estates", "Abbey Falls", "Nagarhole nearby", "honey", "Kodava culture", "Raja's Seat", "trekking"],
    why_go: "The Scotland of India — lush coffee and spice estates, misty hills, rushing waterfalls, and a proud Kodava culture. Best quick escape from Bangalore.",
    not_for: ["party groups", "beach lovers"],
    budget_note: "₹2000–8000/person/day"
  },
  {
    id: "hampi",
    name: "Hampi",
    state_country: "Karnataka, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 30, Mumbai: 12, Bangalore: 8, Chennai: 10, Hyderabad: 6, Kolkata: 36, Pune: 14, Ahmedabad: 18 },
    experience_types: ["heritage", "culture", "offbeat", "adventure"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1500, max_per_day: 5000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [4, 5, 6, 7, 8, 9],
    scores: { romance: 3, adventure: 4, culture: 5, party: 2, nature: 4, family_friendly: 3, spiritual: 4, offbeat: 5, food: 3, safety: 4, solo_friendly: 5 },
    tags: ["Vijayanagara ruins", "boulder hopping", "Virupaksha temple", "Tungabhadra River", "mopeds", "Matanga Hill sunrise", "Hippie Island"],
    why_go: "A surreal UNESCO World Heritage landscape — ancient Vijayanagara empire ruins scattered among giant boulders, with backpacker guesthouses, moped rides, and stunning sunsets.",
    not_for: ["luxury travelers", "families with young kids", "beach lovers"],
    budget_note: "₹1500–5000/person/day. One of India's best budget heritage destinations."
  },
  {
    id: "chikmagalur",
    name: "Chikmagalur",
    state_country: "Karnataka, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 28, Mumbai: 14, Bangalore: 5, Chennai: 7, Hyderabad: 10, Kolkata: 32, Pune: 16, Ahmedabad: 20 },
    experience_types: ["mountains", "nature", "chill", "adventure"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [9, 10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 3, culture: 2, party: 1, nature: 5, family_friendly: 3, spiritual: 1, offbeat: 3, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["coffee estates", "Mullayanagiri", "trekking", "waterfalls", "homestays", "Bababudangiri", "sunrise from peak"],
    why_go: "Karnataka's coffee heartland — plantation stays, the highest peak in Karnataka (Mullayanagiri), and some of the best trekking in South India amidst spice-scented forests.",
    not_for: ["party groups", "beach lovers"],
    budget_note: "₹2000–7000/person/day. Very popular Bangalore weekend destination."
  },
  {
    id: "kabini",
    name: "Kabini + Nagarhole",
    state_country: "Karnataka, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 28, Mumbai: 14, Bangalore: 5, Chennai: 6, Hyderabad: 10, Kolkata: 32, Pune: 16, Ahmedabad: 20 },
    experience_types: ["wildlife", "nature", "luxury"],
    group_fit: ["couple", "family-kids", "friends"],
    budget: { tiers: ["mid", "premium"], min_per_day: 5000, max_per_day: 25000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 4, adventure: 4, culture: 1, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 3, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["tiger", "elephant", "leopard", "boat safari", "Kabini backwaters", "Nagarhole NP", "luxury lodges", "birdwatching"],
    why_go: "South India's finest wildlife experience — Kabini's backwater boat safaris offer close encounters with large elephant herds and good tiger/leopard sightings at premium lodges.",
    not_for: ["budget travelers", "party groups", "beach lovers"],
    budget_note: "₹5000–25000/person/day. Premium lodges push costs high but are worth it."
  },
  {
    id: "gokarna",
    name: "Gokarna",
    state_country: "Karnataka, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 30, Mumbai: 10, Bangalore: 8, Chennai: 10, Hyderabad: 12, Kolkata: 36, Pune: 12, Ahmedabad: 16 },
    experience_types: ["beach", "spiritual", "chill", "offbeat"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 4, max_days: 6 },
    best_months: [10, 11, 12, 1, 2, 3, 4],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 4, adventure: 3, culture: 3, party: 2, nature: 4, family_friendly: 2, spiritual: 4, offbeat: 4, food: 3, safety: 4, solo_friendly: 5 },
    tags: ["Om Beach", "Half Moon Beach", "Paradise Beach", "Mahabaleshwar Temple", "trek between beaches", "hammocks", "hippie vibe"],
    why_go: "Goa's quieter, more spiritual cousin — stunning cove beaches accessible only by foot or boat, a sacred Shiva temple in town, and a genuine backpacker atmosphere without the commercial excess.",
    not_for: ["families with young kids", "luxury travelers", "party groups"],
    budget_note: "₹1500–6000/person/day. One of India's best value beach destinations."
  },
  {
    id: "munnar",
    name: "Munnar",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 34, Mumbai: 20, Bangalore: 6, Chennai: 6, Hyderabad: 12, Kolkata: 38, Pune: 22, Ahmedabad: 26 },
    experience_types: ["mountains", "nature", "chill", "trekking"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2500, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [9, 10, 11, 12, 1, 2, 3, 4],
    avoid_months: [6, 7, 8],
    scores: { romance: 5, adventure: 3, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 2, food: 4, safety: 5, solo_friendly: 3 },
    tags: ["tea estates", "Anamudi peak", "Eravikulam NP", "Neelakurinji", "mist", "cardamom", "Top Station", "Mattupetty Dam"],
    why_go: "Kerala's crown jewel hill station — endless green tea estates rolling into mist-covered peaks. The rare Neelakurinji flowers that bloom every 12 years turn entire hillsides blue.",
    not_for: ["party groups", "beach lovers"],
    budget_note: "₹2500–8000/person/day"
  },
  {
    id: "alleppey",
    name: "Alleppey + Kumarakom (Backwaters)",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 34, Mumbai: 20, Bangalore: 7, Chennai: 6, Hyderabad: 12, Kolkata: 38, Pune: 22, Ahmedabad: 26 },
    experience_types: ["nature", "chill", "romance", "culture"],
    group_fit: ["couple", "family-kids", "friends"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 20000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [9, 10, 11, 12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 5, adventure: 2, culture: 4, party: 1, nature: 5, family_friendly: 4, spiritual: 2, offbeat: 2, food: 5, safety: 5, solo_friendly: 3 },
    tags: ["houseboat", "backwaters", "snake boat race", "Kerala cuisine", "coconut palms", "Vembanad Lake", "Nehru Trophy"],
    why_go: "The quintessential Kerala experience — overnight houseboat through narrow canals flanked by coconut palms, fresh catch Kerala cuisine cooked on board, and total serenity.",
    not_for: ["adventure seekers", "party groups", "solo budget travelers (houseboats price higher alone)"],
    budget_note: "₹3000–20000/person/day. Houseboat ₹7000–25000/night for two."
  },
  {
    id: "wayanad",
    name: "Wayanad",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 32, Mumbai: 18, Bangalore: 5, Chennai: 7, Hyderabad: 11, Kolkata: 36, Pune: 20, Ahmedabad: 24 },
    experience_types: ["nature", "wildlife", "mountains", "chill", "adventure"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [9, 10, 11, 12, 1, 2, 3, 4],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 4, culture: 3, party: 1, nature: 5, family_friendly: 4, spiritual: 2, offbeat: 3, food: 4, safety: 5, solo_friendly: 4 },
    tags: ["Chembra Peak", "Edakkal Caves", "Banasura Sagar Dam", "elephant sighting", "treehouse stays", "bamboo rafting", "tribal culture"],
    why_go: "Kerala's most diverse hill district — trekking to Kerala's third highest peak, prehistoric cave art, elephant spotting, bamboo rafting, and wonderful treehouse stays.",
    not_for: ["party groups", "beach lovers"],
    budget_note: "₹2000–8000/person/day. Popular but less crowded than Munnar."
  },
  {
    id: "varkala",
    name: "Varkala",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 34, Mumbai: 20, Bangalore: 6, Chennai: 5, Hyderabad: 12, Kolkata: 38, Pune: 22, Ahmedabad: 26 },
    experience_types: ["beach", "spiritual", "chill", "yoga"],
    group_fit: ["couple", "solo", "friends"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 2, ideal_days: 4, max_days: 6 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 5, adventure: 2, culture: 3, party: 2, nature: 4, family_friendly: 3, spiritual: 4, offbeat: 3, food: 4, safety: 4, solo_friendly: 5 },
    tags: ["cliff-top beach", "Papanasam beach", "cliff cafes", "yoga retreat", "Janardana Swamy temple", "ayurveda", "sunset"],
    why_go: "Kerala's most beautiful beach — clifftop restaurants overlooking the Arabian Sea, a sacred Hindu temple steps from the shore, and a laid-back backpacker energy unlike anywhere else in Kerala.",
    not_for: ["families with young kids (steep cliffs)", "party groups"],
    budget_note: "₹2000–7000/person/day. Strong yoga/wellness scene."
  },
  {
    id: "fort_kochi",
    name: "Fort Kochi",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 34, Mumbai: 20, Bangalore: 6, Chennai: 6, Hyderabad: 12, Kolkata: 38, Pune: 22, Ahmedabad: 26 },
    experience_types: ["heritage", "culture", "food", "chill"],
    group_fit: ["couple", "friends", "solo", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 4, adventure: 1, culture: 5, party: 2, nature: 2, family_friendly: 4, spiritual: 3, offbeat: 3, food: 5, safety: 5, solo_friendly: 4 },
    tags: ["Chinese fishing nets", "Jew Town", "spice market", "Mattancherry Palace", "Kathakali", "colonial walks", "Kerala seafood", "art galleries"],
    why_go: "Kerala's most culturally layered city — Portuguese, Dutch, Jewish, and British history on one small peninsula, with excellent seafood, heritage art galleries, and languid ferry rides.",
    not_for: ["adventure seekers", "beach lovers"],
    budget_note: "₹2000–8000/person/day. Gateway to Kerala backwaters."
  },
  {
    id: "thekkady",
    name: "Thekkady + Periyar",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 34, Mumbai: 20, Bangalore: 6, Chennai: 6, Hyderabad: 12, Kolkata: 38, Pune: 22, Ahmedabad: 26 },
    experience_types: ["wildlife", "nature", "adventure"],
    group_fit: ["family-kids", "couple", "friends"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2500, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [9, 10, 11, 12, 1, 2, 3, 4],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 5, spiritual: 1, offbeat: 2, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Periyar Lake boat", "elephant sighting", "spice plantation", "tiger reserve", "bamboo rafting", "trekking", "cardamom hills"],
    why_go: "Kerala's premier wildlife reserve — boat safaris on Periyar Lake for elephant and bison sightings, spice plantation walks, and night trekking with tribal guides.",
    not_for: ["beach lovers", "luxury travelers", "party groups"],
    budget_note: "₹2500–8000/person/day"
  },
  {
    id: "pondicherry",
    name: "Pondicherry",
    state_country: "Tamil Nadu / Puducherry, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 32, Mumbai: 22, Bangalore: 4, Chennai: 3, Hyderabad: 12, Kolkata: 36, Pune: 24, Ahmedabad: 28 },
    experience_types: ["heritage", "chill", "beach", "culture", "spiritual"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5],
    avoid_months: [11],
    scores: { romance: 4, adventure: 2, culture: 4, party: 2, nature: 2, family_friendly: 3, spiritual: 4, offbeat: 3, food: 5, safety: 5, solo_friendly: 4 },
    tags: ["French Quarter", "Auroville", "beach boulevard", "cafes", "yellow-and-white streets", "Sri Aurobindo Ashram", "scuba diving", "croissants"],
    why_go: "South India's quirkiest town — French colonial streets with baguettes and espresso next to Tamil temple town, a futuristic spiritual community in Auroville, and free-spirited beach culture.",
    not_for: ["adventure seekers", "luxury beach travelers"],
    budget_note: "₹2000–8000/person/day. Excellent cafe and food scene."
  },
  {
    id: "ooty_kodaikanal",
    name: "Ooty + Kodaikanal",
    state_country: "Tamil Nadu, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 34, Mumbai: 20, Bangalore: 6, Chennai: 5, Hyderabad: 12, Kolkata: 38, Pune: 22, Ahmedabad: 26 },
    experience_types: ["mountains", "nature", "chill", "family"],
    group_fit: ["family-kids", "couple", "friends"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 2, ideal_days: 4, max_days: 5 },
    best_months: [4, 5, 6, 9, 10, 11, 12],
    avoid_months: [],
    scores: { romance: 4, adventure: 2, culture: 2, party: 1, nature: 4, family_friendly: 5, spiritual: 1, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Nilgiri Mountain Railway", "Ooty Lake", "tea gardens", "Doddabetta", "Kodai Lake", "Pine Forest", "chocolate", "Coaker's Walk"],
    why_go: "Tamil Nadu's classic hill station duo — Ooty's toy train and tea gardens for families, Kodaikanal's dramatic shola forests and cliff walks for couples and solo travelers.",
    not_for: ["adventure seekers", "party groups", "offbeat travelers"],
    budget_note: "₹2000–7000/person/day"
  },
  {
    id: "madurai",
    name: "Madurai",
    state_country: "Tamil Nadu, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 34, Mumbai: 22, Bangalore: 7, Chennai: 6, Hyderabad: 14, Kolkata: 40, Pune: 24, Ahmedabad: 28 },
    experience_types: ["spiritual", "heritage", "culture", "food"],
    group_fit: ["family-kids", "couple", "solo", "friends"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1500, max_per_day: 5000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8, 9],
    scores: { romance: 3, adventure: 1, culture: 5, party: 1, nature: 1, family_friendly: 4, spiritual: 5, offbeat: 3, food: 5, safety: 4, solo_friendly: 4 },
    tags: ["Meenakshi Temple", "night temple visit", "jasmine", "kari dosa", "jigarthanda", "temple gopurams", "Thirumalai Nayakkar Palace"],
    why_go: "The Temple City — Meenakshi Amman Temple is a towering architectural marvel that comes alive with ritual, color, and devotion especially during the night puja. Incredible South Indian food.",
    not_for: ["beach lovers", "adventure seekers", "party groups"],
    budget_note: "₹1500–5000/person/day. Very affordable destination."
  },
  {
    id: "rameswaram",
    name: "Rameswaram",
    state_country: "Tamil Nadu, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 36, Mumbai: 24, Bangalore: 9, Chennai: 7, Hyderabad: 16, Kolkata: 42, Pune: 26, Ahmedabad: 30 },
    experience_types: ["pilgrimage", "spiritual", "beach", "offbeat"],
    group_fit: ["family-kids", "couple", "solo"],
    budget: { tiers: ["tight", "budget"], min_per_day: 1000, max_per_day: 4000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3, 4],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 2, adventure: 2, culture: 4, party: 1, nature: 3, family_friendly: 4, spiritual: 5, offbeat: 4, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Ramanathaswamy Temple", "Pamban Bridge", "Dhanushkodi ghost town", "Agni Theertham", "Ram Setu viewpoint", "Adam's Bridge"],
    why_go: "One of the Char Dham — where the Ram Setu begins and the Indian Ocean meets the Bay of Bengal. Dhanushkodi ghost town at India's southernmost tip is hauntingly beautiful.",
    not_for: ["party groups", "luxury travelers", "adventure seekers"],
    budget_note: "₹1000–4000/person/day. Very affordable pilgrimage circuit."
  },
  {
    id: "mahabalipuram",
    name: "Mahabalipuram",
    state_country: "Tamil Nadu, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 32, Mumbai: 22, Bangalore: 4, Chennai: 1, Hyderabad: 12, Kolkata: 36, Pune: 24, Ahmedabad: 28 },
    experience_types: ["heritage", "beach", "culture", "offbeat"],
    group_fit: ["couple", "friends", "solo", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5],
    avoid_months: [11],
    scores: { romance: 3, adventure: 2, culture: 5, party: 2, nature: 3, family_friendly: 4, spiritual: 3, offbeat: 4, food: 4, safety: 5, solo_friendly: 4 },
    tags: ["Shore Temple", "Arjuna's Penance", "Pancha Rathas", "beach", "sculpture school", "UNESCO", "surfing", "seafood"],
    why_go: "A UNESCO World Heritage Site an hour from Chennai — 7th century Pallava rock-cut temples on a beach, a living stone-carving tradition, and fresh seafood by the ocean.",
    not_for: ["party groups", "beach-only travelers"],
    budget_note: "₹2000–7000/person/day. Popular Chennai day trip."
  },
  {
    id: "vizag_araku",
    name: "Vizag + Araku Valley",
    state_country: "Andhra Pradesh, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 24, Mumbai: 20, Bangalore: 10, Chennai: 8, Hyderabad: 10, Kolkata: 22, Pune: 22, Ahmedabad: 26 },
    experience_types: ["beach", "nature", "mountains", "offbeat"],
    group_fit: ["family-kids", "couple", "friends"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 3, adventure: 3, culture: 3, party: 2, nature: 4, family_friendly: 5, spiritual: 2, offbeat: 4, food: 4, safety: 5, solo_friendly: 3 },
    tags: ["Rushikonda beach", "submarine museum", "Araku toy train", "coffee", "Borra Caves", "tribal culture", "Rishikonda", "Kailasagiri"],
    why_go: "Andhra's underrated coastal gem — Vizag for beaches and submarine tours, then the famous Araku Valley train ride through the Eastern Ghats to a coffee-growing tribal heartland.",
    not_for: ["party groups", "luxury travelers"],
    budget_note: "₹1500–6000/person/day. Very affordable South India destination."
  },
  {
    id: "tirupati",
    name: "Tirupati",
    state_country: "Andhra Pradesh, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 28, Mumbai: 18, Bangalore: 4, Chennai: 3, Hyderabad: 8, Kolkata: 36, Pune: 20, Ahmedabad: 24 },
    experience_types: ["pilgrimage", "spiritual"],
    group_fit: ["family-kids", "couple", "solo"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [1, 2, 3, 10, 11, 12],
    avoid_months: [],
    scores: { romance: 2, adventure: 1, culture: 3, party: 1, nature: 3, family_friendly: 5, spiritual: 5, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Venkateswara temple", "world's most visited temple", "darshan", "laddu prasad", "hair donation", "Tirumala hills"],
    why_go: "The world's most visited religious site — Sri Venkateswara Temple on Tirumala Hill draws over 50,000 pilgrims daily. A profound and uniquely Indian spiritual experience.",
    not_for: ["non-Hindu pilgrims (limited entry)", "adventure seekers", "party groups"],
    budget_note: "₹1500–6000/person/day. TTD guest houses very affordable. Special darshan tickets ₹300."
  },
  {
    id: "andaman",
    name: "Andaman Islands",
    state_country: "Andaman & Nicobar, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 4, Mumbai: 3, Bangalore: 3, Chennai: 2, Hyderabad: 3, Kolkata: 2, Pune: 3, Ahmedabad: 4 },
    experience_types: ["beach", "adventure", "nature", "chill"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3500, max_per_day: 15000 },
    duration: { min_days: 5, ideal_days: 7, max_days: 10 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 5, adventure: 5, culture: 2, party: 2, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 4, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["Radhanagar Beach", "scuba diving", "Havelock Island", "Neil Island", "glass-bottom boat", "bioluminescence", "Cellular Jail", "Barefoot Resort"],
    why_go: "India's finest beach and diving destination — Radhanagar Beach ranked Asia's best, crystal-clear water for world-class scuba, and the haunting Cellular Jail for a slice of colonial history.",
    not_for: ["budget travelers (flights expensive)", "short weekend trips"],
    budget_note: "₹3500–15000/person/day. Flights ₹10–20k return. Requires 5+ days to justify cost."
  }
];

// ─── PART 3: WEST + EAST INDIA (18 destinations) ────────────────────────────
const destinations_part3 = [
  {
    id: "goa_north",
    name: "Goa — North (Baga, Calangute, Anjuna)",
    state_country: "Goa, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 16, Mumbai: 8, Bangalore: 8, Chennai: 10, Hyderabad: 10, Kolkata: 28, Pune: 10, Ahmedabad: 14 },
    experience_types: ["beach", "nightlife", "party", "chill"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 2500, max_per_day: 15000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 10 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 3, adventure: 3, culture: 2, party: 5, nature: 3, family_friendly: 2, spiritual: 1, offbeat: 2, food: 5, safety: 4, solo_friendly: 4 },
    tags: ["Baga Beach", "Tito's", "Anjuna flea market", "shacks", "seafood", "water sports", "nightlife", "full moon parties", "Vagator"],
    why_go: "India's party capital — pumping beach clubs, non-stop nightlife from dusk to dawn, incredible seafood shacks, and the freewheeling energy that makes Goa iconic.",
    not_for: ["families with young kids", "spiritual seekers", "peace and quiet lovers"],
    budget_note: "₹2500–15000/person/day. December–January peak is very expensive."
  },
  {
    id: "goa_south",
    name: "Goa — South (Palolem, Agonda, Canacona)",
    state_country: "Goa, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 16, Mumbai: 9, Bangalore: 8, Chennai: 10, Hyderabad: 10, Kolkata: 28, Pune: 11, Ahmedabad: 14 },
    experience_types: ["beach", "chill", "nature", "yoga"],
    group_fit: ["couple", "solo", "friends", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 10000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 10 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 5, adventure: 2, culture: 2, party: 2, nature: 4, family_friendly: 4, spiritual: 2, offbeat: 3, food: 4, safety: 5, solo_friendly: 4 },
    tags: ["Palolem Beach", "Agonda", "hammocks", "yoga retreats", "dolphin watching", "kayaking", "silent discos", "nesting turtles"],
    why_go: "A completely different Goa — Palolem's crescent-shaped bay is one of India's most beautiful beaches, with hammock shacks, dolphin boats, and an easy rhythm that makes you stay longer.",
    not_for: ["party groups", "those wanting busy nightlife"],
    budget_note: "₹2000–10000/person/day. More affordable than North Goa."
  },
  {
    id: "lonavala",
    name: "Lonavala",
    state_country: "Maharashtra, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 22, Mumbai: 2, Bangalore: 16, Chennai: 18, Hyderabad: 14, Kolkata: 36, Pune: 1, Ahmedabad: 8 },
    experience_types: ["mountains", "nature", "chill"],
    group_fit: ["family-kids", "couple", "friends"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [6, 7, 8, 9, 10, 11],
    avoid_months: [],
    scores: { romance: 4, adventure: 3, culture: 1, party: 1, nature: 4, family_friendly: 5, spiritual: 1, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Bhushi Dam", "Tiger's Leap", "chikki", "Karla Caves", "Rajmachi trek", "monsoon waterfalls", "fudge", "toy train"],
    why_go: "Mumbai and Pune's most beloved weekend escape — dramatic monsoon waterfalls, trekking forts, Karla Buddhist caves, and everyone's guilty pleasure: chikki and fudge.",
    not_for: ["adventure seekers wanting remote", "beach lovers", "offbeat travelers"],
    budget_note: "₹2000–7000/person/day. Very affordable weekend drive from Mumbai/Pune."
  },
  {
    id: "mahabaleshwar",
    name: "Mahabaleshwar",
    state_country: "Maharashtra, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 24, Mumbai: 5, Bangalore: 14, Chennai: 16, Hyderabad: 12, Kolkata: 38, Pune: 3, Ahmedabad: 10 },
    experience_types: ["mountains", "nature", "chill", "family"],
    group_fit: ["family-kids", "couple", "friends"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 4, adventure: 2, culture: 2, party: 1, nature: 4, family_friendly: 5, spiritual: 2, offbeat: 1, food: 4, safety: 5, solo_friendly: 3 },
    tags: ["Pratapgad Fort", "Venna Lake", "strawberries", "Arthur's Seat", "Wilson Point sunrise", "corn bhutta", "Panchgani tablelands"],
    why_go: "Maharashtra's most popular hill station — stunning valley viewpoints, strawberry farms you can pick from, Pratapgad Fort, and a classic slow-paced hill town feel.",
    not_for: ["adventure seekers", "party groups", "beach lovers"],
    budget_note: "₹2000–8000/person/day. Very popular Pune weekend destination."
  },
  {
    id: "alibaug",
    name: "Alibaug",
    state_country: "Maharashtra, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 24, Mumbai: 2, Bangalore: 16, Chennai: 18, Hyderabad: 14, Kolkata: 36, Pune: 3, Ahmedabad: 8 },
    experience_types: ["beach", "chill", "nature"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 12000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 4, adventure: 2, culture: 2, party: 2, nature: 3, family_friendly: 4, spiritual: 1, offbeat: 2, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Kolaba Fort", "ferry from Mumbai", "beach resorts", "Kashid Beach nearby", "SUP", "cycling", "villa stays"],
    why_go: "Mumbai's closest beach escape — a quick catamaran ride across the bay to quiet beaches, sea forts, and beach villas. The Colaba Fort walkable from shore at low tide is unique.",
    not_for: ["budget travelers", "party groups", "adventurers wanting more"],
    budget_note: "₹3000–12000/person/day. Resorts expensive on weekends."
  },
  {
    id: "tarkarli",
    name: "Tarkarli",
    state_country: "Maharashtra, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 26, Mumbai: 8, Bangalore: 10, Chennai: 14, Hyderabad: 12, Kolkata: 40, Pune: 10, Ahmedabad: 14 },
    experience_types: ["beach", "adventure", "nature", "offbeat"],
    group_fit: ["friends", "couple", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 4, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 4, food: 4, safety: 5, solo_friendly: 3 },
    tags: ["scuba diving", "snorkeling", "Sindhudurg Fort", "Malvan seafood", "backwaters", "kasav coconut", "clear water"],
    why_go: "Maharashtra's hidden coastal gem — crystal-clear water good for scuba and snorkeling, a magnificent sea fort (Sindhudurg), and incredible Malvani seafood. Far fewer crowds than Goa.",
    not_for: ["party groups", "luxury travelers"],
    budget_note: "₹2000–7000/person/day. Scuba ₹1500–2500/dive."
  },
  {
    id: "rann_of_kutch",
    name: "Rann of Kutch",
    state_country: "Gujarat, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 16, Mumbai: 10, Bangalore: 26, Chennai: 28, Hyderabad: 22, Kolkata: 36, Pune: 12, Ahmedabad: 4 },
    experience_types: ["nature", "culture", "offbeat", "adventure"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 12000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [11, 12, 1, 2],
    avoid_months: [3, 4, 5, 6, 7, 8, 9, 10],
    scores: { romance: 4, adventure: 3, culture: 4, party: 1, nature: 5, family_friendly: 4, spiritual: 2, offbeat: 5, food: 4, safety: 5, solo_friendly: 4 },
    tags: ["white salt desert", "full moon night", "Rann Utsav", "camel rides", "flamingos", "wild ass sanctuary", "Kutchi crafts", "sunset on salt"],
    why_go: "One of India's most extraordinary landscapes — a vast white salt desert stretching to the horizon, magical at full moon during Rann Utsav festival with folk music and handicrafts.",
    not_for: ["beach lovers", "summer travelers (scorching heat)"],
    budget_note: "₹3000–12000/person/day. Rann Utsav tents ₹4000–15000/night. Best: Nov–Feb."
  },
  {
    id: "gir_national_park",
    name: "Gir National Park",
    state_country: "Gujarat, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 20, Mumbai: 10, Bangalore: 24, Chennai: 26, Hyderabad: 20, Kolkata: 36, Pune: 12, Ahmedabad: 6 },
    experience_types: ["wildlife", "nature"],
    group_fit: ["family-kids", "couple", "friends"],
    budget: { tiers: ["mid", "premium"], min_per_day: 4000, max_per_day: 15000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8, 9, 10, 11],
    scores: { romance: 3, adventure: 4, culture: 1, party: 1, nature: 5, family_friendly: 5, spiritual: 1, offbeat: 4, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Asiatic lion", "world's only lion habitat outside Africa", "jeep safari", "leopard", "crocodile", "Kamleshwar dam"],
    why_go: "The only place in the world outside Africa where you can see lions in the wild — Gir's Asiatic lion population has recovered from near-extinction and sightings are near-guaranteed.",
    not_for: ["party groups", "luxury travelers wanting comfort", "beach lovers"],
    budget_note: "₹4000–15000/person/day. Safari permit ₹3000–5000 extra."
  },
  {
    id: "dwarka_somnath",
    name: "Dwarka + Somnath",
    state_country: "Gujarat, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 18, Mumbai: 10, Bangalore: 26, Chennai: 28, Hyderabad: 22, Kolkata: 38, Pune: 12, Ahmedabad: 6 },
    experience_types: ["pilgrimage", "spiritual", "heritage", "beach"],
    group_fit: ["family-kids", "couple", "solo"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8, 9],
    scores: { romance: 2, adventure: 1, culture: 4, party: 1, nature: 3, family_friendly: 5, spiritual: 5, offbeat: 3, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Dwarkadhish Temple", "Somnath Jyotirlinga", "Nageshwar", "Beyt Dwarka island", "Sunset at Somnath", "Chorwad beach", "Bhalka Tirth"],
    why_go: "A sacred Char Dham pilgrimage — Dwarka (Krishna's kingdom) and Somnath (first Jyotirlinga) with the Arabian Sea backdrop and deeply moving temple architecture on the coast.",
    not_for: ["party groups", "adventure seekers", "beach-first travelers"],
    budget_note: "₹1500–6000/person/day. Very affordable pilgrimage circuit."
  },
  {
    id: "darjeeling",
    name: "Darjeeling",
    state_country: "West Bengal, India",
    international: false,
    visa_required: false,
    region: "East India",
    proximity_hours: { Delhi: 16, Mumbai: 32, Bangalore: 40, Chennai: 42, Hyderabad: 36, Kolkata: 8, Pune: 34, Ahmedabad: 28 },
    experience_types: ["mountains", "nature", "culture", "chill"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 6 },
    best_months: [3, 4, 5, 10, 11, 12],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 5, adventure: 3, culture: 4, party: 1, nature: 5, family_friendly: 4, spiritual: 2, offbeat: 3, food: 4, safety: 5, solo_friendly: 4 },
    tags: ["Tiger Hill sunrise", "Kangchenjunga views", "toy train UNESCO", "tea estates", "Ghoom monastery", "Mall Road", "Darjeeling tea"],
    why_go: "The Queen of the Hills — sunrise over Kangchenjunga from Tiger Hill is legendary, the UNESCO toy train chugs through tea estates, and the colonial-era charm is unlike anywhere else.",
    not_for: ["party groups", "beach lovers"],
    budget_note: "₹2000–7000/person/day. Very popular from Kolkata."
  },
  {
    id: "gangtok_sikkim",
    name: "Gangtok + Sikkim",
    state_country: "Sikkim, India",
    international: false,
    visa_required: false,
    region: "East India",
    proximity_hours: { Delhi: 16, Mumbai: 32, Bangalore: 40, Chennai: 42, Hyderabad: 36, Kolkata: 8, Pune: 34, Ahmedabad: 28 },
    experience_types: ["mountains", "spiritual", "nature", "culture", "adventure"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2500, max_per_day: 8000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 10 },
    best_months: [3, 4, 5, 10, 11, 12],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 4, culture: 4, party: 1, nature: 5, family_friendly: 4, spiritual: 5, offbeat: 4, food: 4, safety: 5, solo_friendly: 4 },
    tags: ["Kangchenjunga", "Rumtek Monastery", "Gurudongmar Lake", "MG Marg", "momos", "Nathula Pass", "rhododendrons", "Tsomgo Lake"],
    why_go: "India's cleanest and most spiritual state — sacred Buddhist monasteries, high-altitude glacial lakes near the Tibet border, and rhododendron-covered mountain landscapes.",
    not_for: ["party groups", "beach lovers", "those prone to altitude sickness"],
    budget_note: "₹2500–8000/person/day. Inner line permit needed for some zones."
  },
  {
    id: "meghalaya",
    name: "Meghalaya",
    state_country: "Meghalaya, India",
    international: false,
    visa_required: false,
    region: "Northeast India",
    proximity_hours: { Delhi: 20, Mumbai: 36, Bangalore: 44, Chennai: 46, Hyderabad: 40, Kolkata: 12, Pune: 38, Ahmedabad: 32 },
    experience_types: ["nature", "adventure", "offbeat", "culture"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 8 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 5, culture: 4, party: 2, nature: 5, family_friendly: 3, spiritual: 2, offbeat: 5, food: 4, safety: 4, solo_friendly: 4 },
    tags: ["living root bridges", "Cherrapunji", "Nohkalikai Falls", "Dawki crystal river", "Mawlynnong cleanest village", "caving", "Shillong"],
    why_go: "India's most spectacular Northeast state — living root bridges grown over centuries, the world's wettest region creating stunning waterfalls, and the Dawki river so clear it looks fake.",
    not_for: ["luxury travelers", "families with very young kids", "beach lovers"],
    budget_note: "₹2000–7000/person/day. Incredible value for the experience quality."
  },
  {
    id: "ziro_valley",
    name: "Ziro Valley",
    state_country: "Arunachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "Northeast India",
    proximity_hours: { Delhi: 22, Mumbai: 40, Bangalore: 48, Chennai: 50, Hyderabad: 44, Kolkata: 16, Pune: 42, Ahmedabad: 36 },
    experience_types: ["offbeat", "nature", "culture", "mountains"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 6000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 7 },
    best_months: [3, 4, 5, 10, 11],
    avoid_months: [6, 7, 8, 12, 1, 2],
    scores: { romance: 4, adventure: 4, culture: 5, party: 2, nature: 5, family_friendly: 3, spiritual: 3, offbeat: 5, food: 4, safety: 4, solo_friendly: 4 },
    tags: ["Apatani tribe", "rice fields", "Ziro Music Festival", "bamboo culture", "UNESCO tentative list", "tribal homestays", "pine forests"],
    why_go: "One of India's most extraordinary off-the-beaten-path destinations — a UNESCO tentative site with ancient Apatani tribal culture, terraced rice fields, and the celebrated Ziro Music Festival.",
    not_for: ["luxury travelers", "families with young kids", "short trips"],
    budget_note: "₹2000–6000/person/day. Inner Line Permit needed. Worth every bit of effort."
  },
  {
    id: "kaziranga",
    name: "Kaziranga National Park",
    state_country: "Assam, India",
    international: false,
    visa_required: false,
    region: "Northeast India",
    proximity_hours: { Delhi: 20, Mumbai: 36, Bangalore: 44, Chennai: 46, Hyderabad: 40, Kolkata: 12, Pune: 38, Ahmedabad: 32 },
    experience_types: ["wildlife", "nature", "adventure"],
    group_fit: ["family-kids", "couple", "friends"],
    budget: { tiers: ["mid", "premium"], min_per_day: 4000, max_per_day: 15000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [11, 12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8, 9, 10],
    scores: { romance: 3, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 5, spiritual: 1, offbeat: 4, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["one-horned rhinoceros", "elephant safari", "UNESCO", "tiger", "wild water buffalo", "Brahmaputra flood plains", "birdwatching"],
    why_go: "Home to 2/3rd of the world's one-horned rhinoceros — UNESCO World Heritage park with elephant-back safaris, guaranteed rhino sightings, and excellent tiger and wild buffalo encounters.",
    not_for: ["party groups", "beach lovers", "luxury seekers wanting comfort"],
    budget_note: "₹4000–15000/person/day. Elephant safari ₹1000–2000 extra."
  },
  {
    id: "tawang",
    name: "Tawang",
    state_country: "Arunachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "Northeast India",
    proximity_hours: { Delhi: 24, Mumbai: 40, Bangalore: 50, Chennai: 52, Hyderabad: 46, Kolkata: 16, Pune: 42, Ahmedabad: 38 },
    experience_types: ["spiritual", "mountains", "offbeat", "culture", "adventure"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["mid"], min_per_day: 2500, max_per_day: 8000 },
    duration: { min_days: 5, ideal_days: 7, max_days: 10 },
    best_months: [3, 4, 5, 10, 11],
    avoid_months: [12, 1, 2, 6, 7, 8],
    scores: { romance: 4, adventure: 5, culture: 4, party: 1, nature: 5, spiritual: 5, offbeat: 5, food: 3, family_friendly: 2, safety: 4, solo_friendly: 4 },
    tags: ["Tawang Monastery", "Sela Pass", "Madhuri Lake", "Bumla Pass", "Nuranang Falls", "Buddhist culture", "highest motorable pass", "army camps"],
    why_go: "India's most remote and awe-inspiring destination — a 400-year-old mountaintop monastery, dramatic Sela Pass at 13,000ft, turquoise Madhuri Lake, and a border-area mystique unlike anything.",
    not_for: ["luxury travelers", "families with young kids", "short trips"],
    budget_note: "₹2500–8000/person/day. Inner Line Permit needed. Long but rewarding journey."
  },
  {
    id: "leh_ladakh",
    name: "Leh + Ladakh",
    state_country: "Ladakh, India",
    international: false,
    visa_required: false,
    region: "Ladakh",
    proximity_hours: { Delhi: 6, Mumbai: 8, Bangalore: 8, Chennai: 8, Hyderabad: 8, Kolkata: 8, Pune: 8, Ahmedabad: 8 },
    experience_types: ["mountains", "adventure", "spiritual", "offbeat", "nature"],
    group_fit: ["friends", "solo", "couple"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 15000 },
    duration: { min_days: 5, ideal_days: 8, max_days: 14 },
    best_months: [6, 7, 8, 9],
    avoid_months: [11, 12, 1, 2, 3],
    scores: { romance: 4, adventure: 5, culture: 4, party: 1, nature: 5, family_friendly: 2, spiritual: 5, offbeat: 5, food: 3, safety: 3, solo_friendly: 5 },
    tags: ["Pangong Lake", "Nubra Valley", "Khardung La", "Hemis Monastery", "Chadar trek", "Zanskar", "stargazing", "Magnetic Hill", "royal Leh Palace"],
    why_go: "India's crown jewel — a high-altitude moonscape of turquoise lakes, ancient monasteries, and dramatic mountain passes. Pangong Lake at sunset is one of travel's defining images.",
    not_for: ["families with young kids (altitude)", "luxury-comfort seekers", "those prone to altitude sickness"],
    budget_note: "₹3000–15000/person/day. Fly to Leh — road journey possible via Manali or Srinagar."
  },
  {
    id: "puri_konark",
    name: "Puri + Konark",
    state_country: "Odisha, India",
    international: false,
    visa_required: false,
    region: "East India",
    proximity_hours: { Delhi: 24, Mumbai: 26, Bangalore: 20, Chennai: 14, Hyderabad: 14, Kolkata: 8, Pune: 28, Ahmedabad: 28 },
    experience_types: ["pilgrimage", "spiritual", "heritage", "beach"],
    group_fit: ["family-kids", "couple", "solo"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 3, adventure: 1, culture: 5, party: 1, nature: 3, family_friendly: 5, spiritual: 5, offbeat: 3, food: 4, safety: 4, solo_friendly: 3 },
    tags: ["Jagannath Temple", "Rath Yatra", "Puri beach", "Konark Sun Temple", "UNESCO", "Chilika Lake", "mahaprasad", "Odisha art"],
    why_go: "One of the four Char Dham — the Jagannath Temple is one of Hinduism's most sacred sites, paired with the UNESCO Konark Sun Temple, a stunning 13th century chariot carved in stone.",
    not_for: ["adventure seekers", "party groups", "beach-first travelers"],
    budget_note: "₹1500–6000/person/day. Very affordable. Best during Rath Yatra festival."
  }
];

// ─── PART 4: INTERNATIONAL ASIA (22 destinations) ───────────────────────────
// (Loaded from part4_international_asia.js)

// ─── PART 5: INTERNATIONAL REST (21 destinations) ───────────────────────────
// (Loaded from part5_international_rest.js)

// ─── COMBINED EXPORT ────────────────────────────────────────────────────────
const ALL_DESTINATIONS = [
  ...destinations_part1,
  ...destinations_part2,
  ...destinations_part3,
  // Part 4 and 5 loaded separately; merge in the engine:
  // ...destinations_part4,
  // ...destinations_part5
];

// Note for engine: import part4 and part5 separately and spread into ALL_DESTINATIONS
// Example usage in vibe-quiz.html:
//   const destinations = [...destinations_part1, ...destinations_part2,
//                         ...destinations_part3, ...destinations_part4, ...destinations_part5];

if (typeof module !== 'undefined') {
  module.exports = { ALL_DESTINATIONS, destinations_part1, destinations_part2, destinations_part3 };
}
