// Part 4: International Asia Destinations
// SE Asia (~17 destinations) + Indian Subcontinent (~8 destinations)

const destinations_part4 = [

  // ─── SE ASIA ───────────────────────────────────────────────────────────────

  {
    id: "bali",
    name: "Bali",
    state_country: "Indonesia",
    international: true,
    visa_required: false, // visa on arrival for Indians
    region: "SE Asia",
    proximity_hours: { Delhi: 8, Mumbai: 7, Bangalore: 6, Chennai: 6, Hyderabad: 7, Kolkata: 7, Pune: 7, Ahmedabad: 8 },
    experience_types: ["beach", "nature", "culture", "chill", "adventure", "spiritual"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["mid", "premium"], min_per_day: 5000, max_per_day: 20000 },
    duration: { min_days: 5, ideal_days: 7, max_days: 12 },
    best_months: [4, 5, 6, 7, 8, 9],
    avoid_months: [11, 12, 1, 2],
    scores: { romance: 5, adventure: 3, culture: 4, party: 3, nature: 4, family_friendly: 2, spiritual: 4, offbeat: 1, food: 4, safety: 4, solo_friendly: 4 },
    tags: ["Ubud", "Seminyak", "Uluwatu", "rice terraces", "temples", "surf", "yoga", "nightlife", "beach clubs"],
    why_go: "The quintessential honeymoon and friends' trip destination — beautiful temples, terraced rice fields, beach clubs, and Ubud's wellness scene. Budget needs ₹5000+/person/day to enjoy it properly.",
    not_for: ["budget travelers", "families with young kids", "weekend trips"],
    budget_note: "₹5000–20000/person/day. Flights ₹20–40k return. Min ₹80k/person for a proper 7-day trip."
  },

  {
    id: "bangkok",
    name: "Bangkok",
    state_country: "Thailand",
    international: true,
    visa_required: false,
    region: "SE Asia",
    proximity_hours: { Delhi: 5, Mumbai: 4, Bangalore: 4, Chennai: 4, Hyderabad: 4, Kolkata: 3, Pune: 4, Ahmedabad: 5 },
    experience_types: ["culture", "food", "nightlife", "city", "shopping"],
    group_fit: ["couple", "friends", "solo", "family-kids"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 3000, max_per_day: 15000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 7 },
    best_months: [11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8, 9, 10],
    scores: { romance: 3, adventure: 2, culture: 5, party: 5, nature: 1, family_friendly: 3, spiritual: 3, offbeat: 2, food: 5, safety: 3, solo_friendly: 5 },
    tags: ["street food", "Khao San Road", "temples", "Grand Palace", "rooftop bars", "floating markets", "Chatuchak", "tuk-tuk"],
    why_go: "One of the best food cities in the world, vibrant nightlife, stunning temples, and extremely budget-friendly. Great gateway for first-time SE Asia travelers.",
    not_for: ["nature seekers", "peace and quiet lovers"],
    budget_note: "₹3000–15000/person/day. One of the most affordable international destinations from India."
  },

  {
    id: "phuket",
    name: "Phuket",
    state_country: "Thailand",
    international: true,
    visa_required: false,
    region: "SE Asia",
    proximity_hours: { Delhi: 7, Mumbai: 6, Bangalore: 5, Chennai: 5, Hyderabad: 5, Kolkata: 6, Pune: 6, Ahmedabad: 7 },
    experience_types: ["beach", "nightlife", "chill", "water sports"],
    group_fit: ["couple", "friends"],
    budget: { tiers: ["mid", "premium"], min_per_day: 4500, max_per_day: 18000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 10 },
    best_months: [11, 12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8, 9, 10],
    scores: { romance: 4, adventure: 3, culture: 2, party: 5, nature: 3, family_friendly: 2, spiritual: 1, offbeat: 1, food: 4, safety: 3, solo_friendly: 3 },
    tags: ["Patong Beach", "Phi Phi Islands", "Bangla Road", "snorkeling", "island hopping", "beach clubs", "sunset"],
    why_go: "Thailand's party beach capital with island-hopping to stunning Phi Phi Islands, gorgeous beaches, and buzzing Bangla Road nightlife.",
    not_for: ["families with young kids", "budget travelers", "culture seekers"],
    budget_note: "₹4500–18000/person/day. More expensive than Bangkok but still value for money vs. Bali."
  },

  {
    id: "krabi",
    name: "Krabi",
    state_country: "Thailand",
    international: true,
    visa_required: false,
    region: "SE Asia",
    proximity_hours: { Delhi: 7, Mumbai: 6, Bangalore: 5, Chennai: 5, Hyderabad: 5, Kolkata: 6, Pune: 6, Ahmedabad: 7 },
    experience_types: ["beach", "adventure", "nature", "chill"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 3000, max_per_day: 10000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 8 },
    best_months: [11, 12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8, 9, 10],
    scores: { romance: 5, adventure: 4, culture: 2, party: 2, nature: 5, family_friendly: 3, spiritual: 1, offbeat: 3, food: 3, safety: 4, solo_friendly: 4 },
    tags: ["Railay Beach", "rock climbing", "kayaking", "Four Islands", "Tiger Cave Temple", "longtail boats", "limestone cliffs"],
    why_go: "More laid-back than Phuket with spectacular limestone cliff scenery, world-class rock climbing, and the stunning Railay Beach accessible only by boat.",
    not_for: ["party seekers", "city lovers"],
    budget_note: "₹3000–10000/person/day. More affordable than Phuket, comparable to Goa mid-range."
  },

  {
    id: "chiang_mai",
    name: "Chiang Mai",
    state_country: "Thailand",
    international: true,
    visa_required: false,
    region: "SE Asia",
    proximity_hours: { Delhi: 6, Mumbai: 5, Bangalore: 5, Chennai: 5, Hyderabad: 5, Kolkata: 4, Pune: 5, Ahmedabad: 6 },
    experience_types: ["culture", "nature", "food", "adventure", "spiritual"],
    group_fit: ["couple", "friends", "solo", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2500, max_per_day: 8000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 7 },
    best_months: [11, 12, 1, 2],
    avoid_months: [3, 4, 5, 6, 7, 8, 9, 10],
    scores: { romance: 3, adventure: 4, culture: 5, party: 2, nature: 4, family_friendly: 4, spiritual: 5, offbeat: 3, food: 5, safety: 5, solo_friendly: 5 },
    tags: ["temples", "elephant sanctuary", "night bazaar", "trekking", "cooking class", "Sunday market", "Doi Inthanon"],
    why_go: "Thailand's cultural capital — ancient temples, ethical elephant experiences, incredible food scene, and jungle trekking. One of the safest cities for solo travelers.",
    not_for: ["beach lovers", "party groups"],
    budget_note: "₹2500–8000/person/day. One of SE Asia's best value destinations."
  },

  {
    id: "hanoi",
    name: "Hanoi",
    state_country: "Vietnam",
    international: true,
    visa_required: true,
    region: "SE Asia",
    proximity_hours: { Delhi: 6, Mumbai: 6, Bangalore: 6, Chennai: 5, Hyderabad: 6, Kolkata: 4, Pune: 6, Ahmedabad: 7 },
    experience_types: ["culture", "food", "history", "city"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 4, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3, 4],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 2, culture: 5, party: 2, nature: 2, family_friendly: 3, spiritual: 2, offbeat: 4, food: 5, safety: 4, solo_friendly: 5 },
    tags: ["Hoan Kiem Lake", "Old Quarter", "pho", "bun cha", "street food", "Hoa Lo Prison", "French Quarter", "egg coffee"],
    why_go: "Atmospheric Old Quarter with centuries-old street food culture, stunning lakes, and French colonial architecture. The best food city in SE Asia for adventurous eaters.",
    not_for: ["beach lovers", "adventure seekers"],
    budget_note: "₹2000–8000/person/day. Exceptionally affordable, great for budget travelers."
  },

  {
    id: "halong_bay",
    name: "Ha Long Bay",
    state_country: "Vietnam",
    international: true,
    visa_required: true,
    region: "SE Asia",
    proximity_hours: { Delhi: 6, Mumbai: 6, Bangalore: 6, Chennai: 5, Hyderabad: 6, Kolkata: 4, Pune: 6, Ahmedabad: 7 },
    experience_types: ["nature", "adventure", "chill"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["mid", "premium"], min_per_day: 6000, max_per_day: 20000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [3, 4, 5, 10, 11, 12],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 5, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 3, food: 3, safety: 4, solo_friendly: 3 },
    tags: ["limestone karsts", "cruise", "kayaking", "caves", "overnight boat", "Titop Island", "sunset on deck"],
    why_go: "UNESCO-listed seascape of thousands of limestone islands rising from emerald water — best experienced on an overnight cruise with kayaking through caves.",
    not_for: ["party groups", "budget backpackers (cruises are pricey)"],
    budget_note: "₹6000–20000/person/day. Overnight cruise packages ₹8000–25000/person."
  },

  {
    id: "hoi_an",
    name: "Hoi An",
    state_country: "Vietnam",
    international: true,
    visa_required: true,
    region: "SE Asia",
    proximity_hours: { Delhi: 7, Mumbai: 6, Bangalore: 6, Chennai: 6, Hyderabad: 6, Kolkata: 5, Pune: 6, Ahmedabad: 7 },
    experience_types: ["culture", "food", "chill", "beach"],
    group_fit: ["couple", "friends", "solo", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2500, max_per_day: 9000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 6 },
    best_months: [2, 3, 4, 5, 6, 7, 8],
    avoid_months: [10, 11, 12],
    scores: { romance: 5, adventure: 2, culture: 5, party: 2, nature: 3, family_friendly: 4, spiritual: 2, offbeat: 4, food: 5, safety: 5, solo_friendly: 5 },
    tags: ["lantern town", "Ancient Town", "tailors", "White Rose dumplings", "An Bang Beach", "cycling", "cooking class", "Full Moon lantern festival"],
    why_go: "One of SE Asia's most charming towns — UNESCO heritage Ancient Town glowing with lanterns, incredible local food, legendary tailors, and a peaceful beach nearby.",
    not_for: ["adventure seekers", "party groups"],
    budget_note: "₹2500–9000/person/day. One of the most romantic and affordable destinations in SE Asia."
  },

  {
    id: "ho_chi_minh",
    name: "Ho Chi Minh City (Saigon)",
    state_country: "Vietnam",
    international: true,
    visa_required: true,
    region: "SE Asia",
    proximity_hours: { Delhi: 6, Mumbai: 5, Bangalore: 5, Chennai: 5, Hyderabad: 5, Kolkata: 4, Pune: 5, Ahmedabad: 6 },
    experience_types: ["city", "food", "history", "nightlife"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2500, max_per_day: 9000 },
    duration: { min_days: 2, ideal_days: 4, max_days: 5 },
    best_months: [12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8, 9, 10, 11],
    scores: { romance: 3, adventure: 2, culture: 4, party: 4, nature: 1, family_friendly: 3, spiritual: 1, offbeat: 3, food: 5, safety: 3, solo_friendly: 4 },
    tags: ["Cu Chi Tunnels", "War Remnants Museum", "Bui Vien street", "Pho", "banh mi", "rooftop bars", "District 1", "Mekong Delta day trip"],
    why_go: "Vietnam's energetic southern hub — powerful war history, legendary street food, frenetic motorbike energy, and wild nightlife on Bui Vien Street.",
    not_for: ["nature lovers", "peace seekers", "families with young kids"],
    budget_note: "₹2500–9000/person/day. Affordable and easy for first-time SE Asia travelers."
  },

  {
    id: "siem_reap",
    name: "Siem Reap & Angkor Wat",
    state_country: "Cambodia",
    international: true,
    visa_required: true,
    region: "SE Asia",
    proximity_hours: { Delhi: 6, Mumbai: 6, Bangalore: 5, Chennai: 5, Hyderabad: 5, Kolkata: 4, Pune: 6, Ahmedabad: 7 },
    experience_types: ["heritage", "culture", "history", "spiritual"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 3000, max_per_day: 10000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8, 9, 10],
    scores: { romance: 3, adventure: 2, culture: 5, party: 2, nature: 2, family_friendly: 4, spiritual: 5, offbeat: 3, food: 3, safety: 4, solo_friendly: 4 },
    tags: ["Angkor Wat", "Angkor Thom", "Ta Prohm", "sunrise at Angkor", "tuk-tuk", "Pub Street", "Tonle Sap Lake", "temple complex"],
    why_go: "Home to Angkor Wat — the largest religious monument in the world, a deeply moving sunrise experience, and a stunning array of ancient Khmer temples.",
    not_for: ["beach lovers", "party groups", "those seeking modern comforts"],
    budget_note: "₹3000–10000/person/day. Angkor pass: ₹2500 (1-day) to ₹6000 (3-day). Very affordable."
  },

  {
    id: "singapore",
    name: "Singapore",
    state_country: "Singapore",
    international: true,
    visa_required: false,
    region: "SE Asia",
    proximity_hours: { Delhi: 6, Mumbai: 5, Bangalore: 5, Chennai: 4, Hyderabad: 5, Kolkata: 4, Pune: 5, Ahmedabad: 6 },
    experience_types: ["city", "food", "family", "shopping", "luxury"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["mid", "premium"], min_per_day: 8000, max_per_day: 30000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 7 },
    best_months: [2, 3, 4, 5, 6, 7, 8, 9],
    avoid_months: [],
    scores: { romance: 3, adventure: 2, culture: 4, party: 3, nature: 2, family_friendly: 5, spiritual: 1, offbeat: 1, food: 5, safety: 5, solo_friendly: 5 },
    tags: ["Gardens by the Bay", "Marina Bay Sands", "Sentosa", "Universal Studios", "hawker centres", "Little India", "Chinatown", "night safari"],
    why_go: "The most family-friendly international destination from India — world-class safety, incredible food across cuisines, Universal Studios, and night safari. No visa needed.",
    not_for: ["budget travelers", "adventure seekers", "offbeat travel lovers"],
    budget_note: "₹8000–30000/person/day. One of Asia's most expensive cities. Budget min ₹1.2L/person for 5 days."
  },

  {
    id: "kuala_lumpur",
    name: "Kuala Lumpur",
    state_country: "Malaysia",
    international: true,
    visa_required: false,
    region: "SE Asia",
    proximity_hours: { Delhi: 6, Mumbai: 5, Bangalore: 5, Chennai: 4, Hyderabad: 5, Kolkata: 4, Pune: 5, Ahmedabad: 6 },
    experience_types: ["city", "food", "shopping", "culture"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 3000, max_per_day: 12000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 6 },
    best_months: [5, 6, 7, 8, 9],
    avoid_months: [10, 11, 12, 1, 2],
    scores: { romance: 3, adventure: 2, culture: 4, party: 3, nature: 2, family_friendly: 4, spiritual: 2, offbeat: 2, food: 5, safety: 4, solo_friendly: 4 },
    tags: ["Petronas Towers", "Batu Caves", "Jalan Alor", "Little India", "Chinatown", "KLCC", "Genting Highlands", "Indian food"],
    why_go: "Affordable, diverse, and great for first-time international travelers. Fantastic Indian food (large Tamil/Malayali community), Batu Caves, and iconic Petronas Towers.",
    not_for: ["beach lovers", "nature seekers", "offbeat travelers"],
    budget_note: "₹3000–12000/person/day. Very affordable for Indians, especially on food."
  },

  {
    id: "langkawi",
    name: "Langkawi",
    state_country: "Malaysia",
    international: true,
    visa_required: false,
    region: "SE Asia",
    proximity_hours: { Delhi: 7, Mumbai: 6, Bangalore: 5, Chennai: 5, Hyderabad: 5, Kolkata: 5, Pune: 6, Ahmedabad: 7 },
    experience_types: ["beach", "nature", "chill", "adventure"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 3500, max_per_day: 12000 },
    duration: { min_days: 4, ideal_days: 5, max_days: 7 },
    best_months: [11, 12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8, 9, 10],
    scores: { romance: 5, adventure: 3, culture: 2, party: 2, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 3, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["duty-free", "Cenang Beach", "mangrove kayaking", "Eagle Square", "cable car", "island hopping", "luxury resorts"],
    why_go: "Malaysia's most scenic island — duty-free shopping, lush rainforest, mangrove boat rides, and some of the most affordable luxury resorts in SE Asia.",
    not_for: ["city lovers", "culture seekers", "party groups"],
    budget_note: "₹3500–12000/person/day. Duty-free island — alcohol and goods cheaper here."
  },

  {
    id: "penang",
    name: "Penang",
    state_country: "Malaysia",
    international: true,
    visa_required: false,
    region: "SE Asia",
    proximity_hours: { Delhi: 7, Mumbai: 6, Bangalore: 5, Chennai: 5, Hyderabad: 5, Kolkata: 5, Pune: 6, Ahmedabad: 7 },
    experience_types: ["food", "culture", "heritage", "city"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2500, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [1, 2, 3, 6, 7, 8, 9],
    avoid_months: [10, 11, 12, 4, 5],
    scores: { romance: 3, adventure: 1, culture: 5, party: 2, nature: 2, family_friendly: 4, spiritual: 3, offbeat: 4, food: 5, safety: 5, solo_friendly: 5 },
    tags: ["George Town", "street food", "street art", "char kway teow", "Little India", "Penang Hill", "UNESCO Old Town", "hawker stalls"],
    why_go: "Asia's food capital with a distinct Peranakan culture, UNESCO-listed George Town, incredible street art, and the most famous street food scene in SE Asia.",
    not_for: ["beach lovers", "party groups", "nature seekers"],
    budget_note: "₹2500–8000/person/day. One of the most affordable international destinations."
  },

  {
    id: "palawan",
    name: "El Nido, Palawan",
    state_country: "Philippines",
    international: true,
    visa_required: false,
    region: "SE Asia",
    proximity_hours: { Delhi: 9, Mumbai: 8, Bangalore: 7, Chennai: 7, Hyderabad: 8, Kolkata: 7, Pune: 8, Ahmedabad: 9 },
    experience_types: ["beach", "nature", "adventure", "chill"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["mid", "premium"], min_per_day: 5000, max_per_day: 18000 },
    duration: { min_days: 5, ideal_days: 7, max_days: 10 },
    best_months: [11, 12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8, 9, 10],
    scores: { romance: 5, adventure: 5, culture: 2, party: 2, nature: 5, family_friendly: 2, spiritual: 1, offbeat: 4, food: 3, safety: 3, solo_friendly: 4 },
    tags: ["Big Lagoon", "Secret Lagoon", "island hopping", "kayaking", "coral reefs", "white sand", "limestone cliffs", "Puerto Princesa"],
    why_go: "Consistently rated one of the world's best islands — surreal limestone cliff lagoons, world-class snorkeling, and pristine beaches that feel untouched.",
    not_for: ["families with young kids", "budget travelers", "city lovers", "short trips"],
    budget_note: "₹5000–18000/person/day. Longer travel time from India — worth it only for 7+ days."
  },

  {
    id: "boracay",
    name: "Boracay",
    state_country: "Philippines",
    international: true,
    visa_required: false,
    region: "SE Asia",
    proximity_hours: { Delhi: 9, Mumbai: 8, Bangalore: 7, Chennai: 7, Hyderabad: 8, Kolkata: 7, Pune: 8, Ahmedabad: 9 },
    experience_types: ["beach", "nightlife", "water sports", "chill"],
    group_fit: ["couple", "friends"],
    budget: { tiers: ["mid", "premium"], min_per_day: 5000, max_per_day: 18000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 8 },
    best_months: [11, 12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8, 9, 10],
    scores: { romance: 5, adventure: 3, culture: 1, party: 4, nature: 4, family_friendly: 2, spiritual: 1, offbeat: 2, food: 3, safety: 3, solo_friendly: 3 },
    tags: ["White Beach", "D'Mall", "parasailing", "kitesurfing", "sunset sailing", "beach bars", "Station 2"],
    why_go: "The most famous beach in the Philippines — stunning White Beach, world-class kitesurfing, vibrant beach bar scene. More accessible than Palawan.",
    not_for: ["nature purists", "families with young kids", "budget travelers"],
    budget_note: "₹5000–18000/person/day. Similar cost to Bali but longer flight."
  },

  // ─── INDIAN SUBCONTINENT ────────────────────────────────────────────────────

  {
    id: "sri_lanka",
    name: "Sri Lanka",
    state_country: "Sri Lanka",
    international: true,
    visa_required: true, // ETA online
    region: "Indian Subcontinent",
    proximity_hours: { Delhi: 4, Mumbai: 3, Bangalore: 2, Chennai: 2, Hyderabad: 3, Kolkata: 4, Pune: 3, Ahmedabad: 4 },
    experience_types: ["culture", "nature", "beach", "wildlife", "heritage", "spiritual"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 3000, max_per_day: 12000 },
    duration: { min_days: 5, ideal_days: 8, max_days: 14 },
    best_months: [12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8, 9, 10, 11],
    scores: { romance: 4, adventure: 3, culture: 5, party: 1, nature: 5, family_friendly: 5, spiritual: 5, offbeat: 3, food: 4, safety: 4, solo_friendly: 4 },
    tags: ["Sigiriya", "Kandy Temple", "tea estates", "Ella", "Mirissa beach", "whale watching", "Colombo", "leopards", "Yala NP", "train through hills"],
    why_go: "India's island neighbor packs extraordinary diversity — ancient rock fortresses, Buddhist temples, whale watching, tea plantation trains, and beaches, all within reach of South India.",
    not_for: ["party groups", "short weekend trips"],
    budget_note: "₹3000–12000/person/day. Very affordable from South India (2h flight). ETA visa ₹1500."
  },

  {
    id: "bhutan",
    name: "Bhutan",
    state_country: "Bhutan",
    international: true,
    visa_required: true, // permit required, not standard visa
    region: "Indian Subcontinent",
    proximity_hours: { Delhi: 4, Mumbai: 5, Bangalore: 6, Chennai: 6, Hyderabad: 5, Kolkata: 2, Pune: 5, Ahmedabad: 5 },
    experience_types: ["spiritual", "culture", "nature", "mountains", "offbeat"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["mid", "premium"], min_per_day: 8000, max_per_day: 20000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 8 },
    best_months: [3, 4, 5, 10, 11],
    avoid_months: [6, 7, 8, 12, 1, 2],
    scores: { romance: 4, adventure: 3, culture: 5, party: 1, nature: 5, family_friendly: 4, spiritual: 5, offbeat: 5, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["Tiger's Nest", "Paro", "Thimphu", "dzongs", "GNH", "archery", "monasteries", "clean air", "no traffic lights"],
    why_go: "The happiest country on Earth — pristine Himalayan landscapes, Tiger's Nest monastery clinging to a cliff, ancient dzongs, and a culture that prioritizes happiness over GDP.",
    not_for: ["party groups", "budget travelers", "beach lovers", "weekend trips"],
    budget_note: "₹8000–20000/person/day. Mandatory Sustainable Development Fee: ₹2100/person/night for Indians."
  },

  {
    id: "nepal_pokhara",
    name: "Nepal — Kathmandu & Pokhara",
    state_country: "Nepal",
    international: true,
    visa_required: true, // visa on arrival
    region: "Indian Subcontinent",
    proximity_hours: { Delhi: 2, Mumbai: 3, Bangalore: 4, Chennai: 4, Hyderabad: 3, Kolkata: 2, Pune: 3, Ahmedabad: 3 },
    experience_types: ["mountains", "adventure", "spiritual", "culture", "nature"],
    group_fit: ["couple", "friends", "solo", "family-kids"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2500, max_per_day: 10000 },
    duration: { min_days: 4, ideal_days: 7, max_days: 14 },
    best_months: [3, 4, 5, 10, 11],
    avoid_months: [6, 7, 8, 12, 1, 2],
    scores: { romance: 4, adventure: 5, culture: 4, party: 2, nature: 5, family_friendly: 3, spiritual: 5, offbeat: 3, food: 3, safety: 4, solo_friendly: 5 },
    tags: ["Everest Base Camp", "Annapurna trek", "Pashupati temple", "paragliding Pokhara", "Fewa Lake", "Boudhanath", "Himalayan views"],
    why_go: "The ultimate adventure destination — world's greatest treks, paragliding over Annapurna, sacred Hindu temples, and Himalayan views that leave you speechless.",
    not_for: ["beach lovers", "luxury travelers who want convenience"],
    budget_note: "₹2500–10000/person/day. Very affordable. Visa on arrival ₹2000 (15 days)."
  },

  {
    id: "maldives",
    name: "Maldives",
    state_country: "Maldives",
    international: true,
    visa_required: false,
    region: "Indian Subcontinent",
    proximity_hours: { Delhi: 5, Mumbai: 4, Bangalore: 3, Chennai: 3, Hyderabad: 3, Kolkata: 5, Pune: 4, Ahmedabad: 4 },
    experience_types: ["beach", "luxury", "chill", "romance"],
    group_fit: ["couple"],
    budget: { tiers: ["premium"], min_per_day: 15000, max_per_day: 80000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 8 },
    best_months: [11, 12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8, 9, 10],
    scores: { romance: 5, adventure: 2, culture: 1, party: 1, nature: 4, family_friendly: 2, spiritual: 1, offbeat: 1, food: 3, safety: 5, solo_friendly: 1 },
    tags: ["overwater villa", "bioluminescent beach", "snorkeling", "whale sharks", "private island", "underwater restaurant", "water bungalow"],
    why_go: "The world's most romantic destination — crystal-clear turquoise water, overwater villas, and complete seclusion. The quintessential honeymoon experience.",
    not_for: ["budget travelers", "families with kids", "solo travelers", "culture seekers", "adventure groups"],
    budget_note: "₹15000–80000/person/day. Min ₹1.5L/person for 5 days. Premium-only destination."
  },

  {
    id: "colombo_galle",
    name: "Colombo & Galle",
    state_country: "Sri Lanka",
    international: true,
    visa_required: true,
    region: "Indian Subcontinent",
    proximity_hours: { Delhi: 4, Mumbai: 3, Bangalore: 2, Chennai: 2, Hyderabad: 3, Kolkata: 4, Pune: 3, Ahmedabad: 4 },
    experience_types: ["city", "heritage", "food", "beach", "culture"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2500, max_per_day: 10000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 6 },
    best_months: [12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8, 9, 10, 11],
    scores: { romance: 4, adventure: 2, culture: 4, party: 2, nature: 3, family_friendly: 4, spiritual: 3, offbeat: 3, food: 4, safety: 4, solo_friendly: 4 },
    tags: ["Galle Fort", "Dutch architecture", "Colombo food scene", "Mirissa nearby", "stilt fishermen", "cinnamon", "cricket grounds"],
    why_go: "The classic Sri Lanka intro — colonial Galle Fort, vibrant Colombo food scene, and easy access to the southern beaches. Perfect 3–4 day add-on to a longer Sri Lanka trip.",
    not_for: ["adventure seekers", "trekkers"],
    budget_note: "₹2500–10000/person/day. One of the most affordable international trips from South India."
  }

];

// Export for use in main destinations file
if (typeof module !== 'undefined') {
  module.exports = destinations_part4;
}
