// PART 3 — Domestic: West India (Goa, Maharashtra, Gujarat) + East/Northeast India + Ladakh/Andaman

const WEST_EAST_INDIA = [

  // ── WEST INDIA ──────────────────────────────────────────────────────

  {
    id: "goa_north",
    name: "Goa (North Goa)",
    state_country: "Goa, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 20, Mumbai: 8, Bangalore: 8, Chennai: 14, Hyderabad: 12, Kolkata: 28, Pune: 8, Ahmedabad: 12 },
    experience_types: ["beach", "party", "food", "chill", "nightlife"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 1500, max_per_day: 8000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 7 },
    best_months: [11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 2, culture: 2, party: 5, nature: 3, family_friendly: 2, spiritual: 1, offbeat: 1, food: 5, safety: 4, solo_friendly: 4 },
    tags: ["Baga Beach", "Calangute", "Anjuna flea market", "beach shacks", "nightclubs", "water sports", "casinos", "sunsets"],
    why_go: "India's party capital — beach shacks, sunsets, clubs, flea markets. North Goa is the most energetic beach destination in India.",
    not_for: ["families with young kids", "pilgrimage seekers", "those wanting peace and quiet"],
    budget_note: "₹1500–8000/person/day; peaks Dec-Jan"
  },

  {
    id: "goa_south",
    name: "Goa (South Goa)",
    state_country: "Goa, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 20, Mumbai: 8, Bangalore: 8, Chennai: 14, Hyderabad: 12, Kolkata: 28, Pune: 8, Ahmedabad: 12 },
    experience_types: ["beach", "chill", "romance", "food", "nature"],
    group_fit: ["couple", "family-kids", "friends", "solo-female"],
    budget: { tiers: ["mid", "premium"], min_per_day: 2500, max_per_day: 12000 },
    duration: { min_days: 3, ideal_days: 5, max_days: 7 },
    best_months: [11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 5, adventure: 2, culture: 3, party: 2, nature: 4, family_friendly: 4, spiritual: 1, offbeat: 2, food: 4, safety: 5, solo_friendly: 3 },
    tags: ["Palolem Beach", "Agonda Beach", "Butterfly Beach", "calm waters", "kayaking", "Cabo de Rama fort", "dolphin tours"],
    why_go: "Palolem and Agonda are India's most beautiful calm beaches — quiet, romantic, with gentle waves safe for kids.",
    not_for: ["party seekers", "nightlife hunters"],
    budget_note: "₹2500–12000/person/day; worth paying more for South Goa properties"
  },

  {
    id: "lonavala_khandala",
    name: "Lonavala + Khandala",
    state_country: "Maharashtra, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 24, Mumbai: 2, Bangalore: 12, Chennai: 16, Hyderabad: 10, Kolkata: 28, Pune: 1, Ahmedabad: 8 },
    experience_types: ["mountains", "monsoon", "nature", "chill", "family"],
    group_fit: ["couple", "family-kids", "friends"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1200, max_per_day: 6000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [6, 7, 8, 9, 10, 11, 12],
    avoid_months: [4, 5],
    scores: { romance: 3, adventure: 2, culture: 1, party: 1, nature: 4, family_friendly: 5, spiritual: 1, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Bhushi Dam", "Tiger's Leap", "monsoon waterfalls", "chikki", "fog", "trekking", "Duke's Nose"],
    why_go: "Mumbai and Pune's favorite monsoon escape — Bhushi Dam overflow, waterfalls, and misty ghats.",
    not_for: ["adventure seekers", "party groups", "long trips", "summer heat"],
    budget_note: "₹1200–6000/person/day; very accessible"
  },

  {
    id: "mahabaleshwar",
    name: "Mahabaleshwar",
    state_country: "Maharashtra, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 24, Mumbai: 5, Bangalore: 12, Chennai: 16, Hyderabad: 10, Kolkata: 28, Pune: 3, Ahmedabad: 10 },
    experience_types: ["mountains", "nature", "chill", "family"],
    group_fit: ["couple", "family-kids", "family-elderly"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 1, culture: 1, party: 1, nature: 4, family_friendly: 5, spiritual: 1, offbeat: 1, food: 4, safety: 5, solo_friendly: 3 },
    tags: ["strawberries", "Arthur's Seat", "Venna Lake", "Panchgani", "mulberry", "sunset point", "horse rides"],
    why_go: "Maharashtra's most popular hill station — Venna Lake boating, fresh strawberries, and beautiful valley views.",
    not_for: ["adventure seekers", "party groups", "monsoon visits"],
    budget_note: "₹2000–7000/person/day"
  },

  {
    id: "alibaug",
    name: "Alibaug",
    state_country: "Maharashtra, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 26, Mumbai: 2, Bangalore: 14, Chennai: 18, Hyderabad: 12, Kolkata: 30, Pune: 3, Ahmedabad: 10 },
    experience_types: ["beach", "chill", "nature"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 2000, max_per_day: 12000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 1, culture: 2, party: 2, nature: 3, family_friendly: 4, spiritual: 1, offbeat: 2, food: 3, safety: 5, solo_friendly: 2 },
    tags: ["Alibaug Beach", "Kolaba Fort", "ferry from Gateway of India", "beach resorts", "Kashid Beach", "seafood"],
    why_go: "Mumbai's closest beach escape — 2hr ferry ride, beautiful Kashid Beach, good resorts for weekend unwinding.",
    not_for: ["adventure seekers", "long trips", "party groups"],
    budget_note: "₹2000–12000/person/day; resorts pricier on weekends"
  },

  {
    id: "tarkarli",
    name: "Tarkarli",
    state_country: "Maharashtra, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 28, Mumbai: 8, Bangalore: 10, Chennai: 16, Hyderabad: 12, Kolkata: 32, Pune: 7, Ahmedabad: 14 },
    experience_types: ["beach", "scuba diving", "nature", "offbeat", "chill"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1200, max_per_day: 5000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 3, culture: 2, party: 1, nature: 4, family_friendly: 4, spiritual: 1, offbeat: 4, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["crystal clear water", "scuba diving", "snorkeling", "Sindhudurg fort", "Malvan", "Konkan coast", "seafood"],
    why_go: "Maharashtra's hidden beach gem — crystal clear water, budget scuba diving, and incredible Konkani seafood.",
    not_for: ["party seekers", "luxury travelers", "monsoon visits"],
    budget_note: "₹1200–5000/person/day; very budget friendly vs Goa"
  },

  {
    id: "rann_of_kutch",
    name: "Rann of Kutch",
    state_country: "Gujarat, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 16, Mumbai: 10, Bangalore: 22, Chennai: 26, Hyderabad: 18, Kolkata: 26, Pune: 10, Ahmedabad: 5 },
    experience_types: ["desert", "offbeat", "culture", "nature", "heritage"],
    group_fit: ["couple", "friends", "family-elderly", "solo"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 2000, max_per_day: 10000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [11, 12, 1, 2],
    avoid_months: [5, 6, 7, 8, 9, 10],
    scores: { romance: 5, adventure: 2, culture: 5, party: 1, nature: 5, family_friendly: 4, spiritual: 2, offbeat: 5, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["white salt desert", "Rann Utsav festival", "full moon night", "flamingos", "Kutchi crafts", "folk music", "Dhordo tent city"],
    why_go: "India's most surreal landscape — the white salt desert under a full moon during Rann Utsav is otherworldly.",
    not_for: ["summer visits", "beach lovers", "adventure trekkers"],
    budget_note: "₹2000–10000/person/day; Rann Utsav tent city ₹8000+ per night"
  },

  {
    id: "gir_national_park",
    name: "Gir National Park",
    state_country: "Gujarat, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 20, Mumbai: 12, Bangalore: 24, Chennai: 28, Hyderabad: 18, Kolkata: 30, Pune: 12, Ahmedabad: 6 },
    experience_types: ["wildlife", "nature", "adventure"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 10000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [12, 1, 2, 3, 4, 5, 6],
    avoid_months: [7, 8, 9, 10, 11],
    scores: { romance: 2, adventure: 4, culture: 1, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 3, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Asiatic lion safari", "only lions in Asia outside Africa", "jeep safari", "Somnath nearby", "jungle lodge"],
    why_go: "The only place in the world outside Africa to spot Asiatic lions in the wild. A must for wildlife lovers.",
    not_for: ["monsoon visits", "party groups", "budget backpackers"],
    budget_note: "₹3000–10000/person/day; safari fees ₹1000–2000 extra"
  },

  {
    id: "dwarka_somnath",
    name: "Dwarka + Somnath",
    state_country: "Gujarat, India",
    international: false,
    visa_required: false,
    region: "West India",
    proximity_hours: { Delhi: 18, Mumbai: 12, Bangalore: 26, Chennai: 30, Hyderabad: 20, Kolkata: 30, Pune: 12, Ahmedabad: 7 },
    experience_types: ["spiritual", "pilgrimage", "heritage", "beach"],
    group_fit: ["family-elderly", "couple", "solo"],
    budget: { tiers: ["tight", "budget"], min_per_day: 800, max_per_day: 3000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 2, adventure: 1, culture: 4, party: 1, nature: 3, family_friendly: 3, spiritual: 5, offbeat: 2, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["Dwarkadhish temple", "Somnath Jyotirlinga", "Nageshwar temple", "Beyt Dwarka island", "sunset aarti"],
    why_go: "Two of Hinduism's holiest sites — Dwarkadhish temple and Somnath Jyotirlinga — on the Gujarat coast.",
    not_for: ["non-religious travelers", "adventure seekers", "beach party travelers"],
    budget_note: "₹800–3000/person/day; very affordable"
  },

  // ── EAST & NORTHEAST INDIA ────────────────────────────────────────

  {
    id: "darjeeling",
    name: "Darjeeling",
    state_country: "West Bengal, India",
    international: false,
    visa_required: false,
    region: "East India",
    proximity_hours: { Delhi: 22, Mumbai: 28, Bangalore: 32, Chennai: 34, Hyderabad: 28, Kolkata: 4, Pune: 28, Ahmedabad: 28 },
    experience_types: ["mountains", "nature", "culture", "chill", "tea estates"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1200, max_per_day: 5000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [3, 4, 5, 9, 10, 11],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 2, culture: 4, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 2, food: 4, safety: 5, solo_friendly: 4 },
    tags: ["Kanchenjunga views", "toy train", "tea gardens", "Tiger Hill sunrise", "Batasia Loop", "momos", "Darjeeling tea"],
    why_go: "Kanchenjunga at sunrise from Tiger Hill, the iconic toy train, and the world's finest teas — East India's crown jewel.",
    not_for: ["party groups", "monsoon trips (very foggy)"],
    budget_note: "₹1200–5000/person/day"
  },

  {
    id: "gangtok_sikkim",
    name: "Gangtok + Sikkim",
    state_country: "Sikkim, India",
    international: false,
    visa_required: false,
    region: "East India",
    proximity_hours: { Delhi: 24, Mumbai: 30, Bangalore: 34, Chennai: 36, Hyderabad: 30, Kolkata: 5, Pune: 30, Ahmedabad: 30 },
    experience_types: ["mountains", "nature", "culture", "adventure", "trekking"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 8 },
    best_months: [3, 4, 5, 9, 10, 11],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 4, culture: 4, party: 1, nature: 5, family_friendly: 3, spiritual: 3, offbeat: 3, food: 4, safety: 5, solo_friendly: 4 },
    tags: ["Kanchenjunga", "Tsomgo Lake", "Nathula Pass", "monasteries", "Sandakphu trek", "Pelling", "yak rides", "thukpa"],
    why_go: "Buddhist monasteries, Himalayan lakes, and Kanchenjunga views — Sikkim feels like a different country.",
    not_for: ["party groups", "beach lovers", "monsoon visits"],
    budget_note: "₹1500–6000/person/day; permit required for some areas"
  },

  {
    id: "meghalaya",
    name: "Meghalaya (Shillong + Cherrapunji + Dawki)",
    state_country: "Meghalaya, India",
    international: false,
    visa_required: false,
    region: "Northeast India",
    proximity_hours: { Delhi: 26, Mumbai: 32, Bangalore: 36, Chennai: 38, Hyderabad: 32, Kolkata: 8, Pune: 32, Ahmedabad: 32 },
    experience_types: ["nature", "offbeat", "adventure", "culture", "monsoon", "trekking"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1200, max_per_day: 5000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 8 },
    best_months: [10, 11, 12, 1, 2, 3, 6, 7],
    avoid_months: [],
    scores: { romance: 4, adventure: 4, culture: 4, party: 1, nature: 5, family_friendly: 2, spiritual: 1, offbeat: 5, food: 3, safety: 4, solo_friendly: 4 },
    tags: ["living root bridges", "Dawki crystal river", "Mawlynnong cleanest village", "Nohkalikai Falls", "Mawsmai Cave", "cloud forests"],
    why_go: "Living root bridges, a crystal-clear river at Dawki, Asia's cleanest village — Northeast India's most magical destination.",
    not_for: ["families with very young kids", "luxury seekers", "party groups"],
    budget_note: "₹1200–5000/person/day"
  },

  {
    id: "ziro_valley",
    name: "Ziro Valley",
    state_country: "Arunachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "Northeast India",
    proximity_hours: { Delhi: 30, Mumbai: 36, Bangalore: 40, Chennai: 42, Hyderabad: 36, Kolkata: 14, Pune: 36, Ahmedabad: 36 },
    experience_types: ["offbeat", "culture", "nature", "tribal", "music festival"],
    group_fit: ["friends", "solo", "couple"],
    budget: { tiers: ["tight", "budget"], min_per_day: 1000, max_per_day: 3000 },
    duration: { min_days: 4, ideal_days: 5, max_days: 7 },
    best_months: [9, 10, 3, 4, 5],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 3, culture: 5, party: 2, nature: 5, family_friendly: 1, spiritual: 2, offbeat: 5, food: 3, safety: 4, solo_friendly: 4 },
    tags: ["Apatani tribe", "Ziro Music Festival", "UNESCO nomination", "pine forests", "rice fields", "tribal homestays"],
    why_go: "One of India's most offbeat destinations — Apatani tribal culture, Ziro Music Festival (Sep), and pristine pine valleys.",
    not_for: ["families", "luxury seekers", "those wanting easy access"],
    budget_note: "₹1000–3000/person/day; inner line permit required"
  },

  {
    id: "kaziranga",
    name: "Kaziranga National Park",
    state_country: "Assam, India",
    international: false,
    visa_required: false,
    region: "Northeast India",
    proximity_hours: { Delhi: 28, Mumbai: 34, Bangalore: 38, Chennai: 40, Hyderabad: 34, Kolkata: 10, Pune: 34, Ahmedabad: 34 },
    experience_types: ["wildlife", "nature", "adventure"],
    group_fit: ["friends", "couple", "family-kids"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 12000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [11, 12, 1, 2, 3, 4],
    avoid_months: [5, 6, 7, 8, 9, 10],
    scores: { romance: 2, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 3, food: 3, safety: 4, solo_friendly: 3 },
    tags: ["one-horned rhinoceros", "UNESCO Heritage", "elephant safari", "jeep safari", "wild buffalo", "Royal Bengal tigers"],
    why_go: "World's largest population of one-horned rhinos — UNESCO site, elephant safari at dawn is breathtaking.",
    not_for: ["monsoon visits", "party groups", "beach lovers"],
    budget_note: "₹3000–12000/person/day; safaris ₹2000–4000 extra"
  },

  {
    id: "tawang",
    name: "Tawang",
    state_country: "Arunachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "Northeast India",
    proximity_hours: { Delhi: 32, Mumbai: 38, Bangalore: 42, Chennai: 44, Hyderabad: 38, Kolkata: 14, Pune: 38, Ahmedabad: 38 },
    experience_types: ["mountains", "culture", "spiritual", "offbeat", "nature"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 5000 },
    duration: { min_days: 5, ideal_days: 7, max_days: 10 },
    best_months: [3, 4, 5, 9, 10],
    avoid_months: [6, 7, 8, 12, 1, 2],
    scores: { romance: 4, adventure: 3, culture: 5, party: 1, nature: 5, family_friendly: 1, spiritual: 5, offbeat: 5, food: 3, safety: 4, solo_friendly: 3 },
    tags: ["Tawang Monastery (India's largest)", "Bum La Pass", "Madhuri Lake", "Sela Pass", "Nuranang Falls", "Tibetan culture"],
    why_go: "India's largest Buddhist monastery at 10,000 feet — a remote, spiritual, and stunningly beautiful destination.",
    not_for: ["families with young kids", "beach lovers", "short trips", "winter travel"],
    budget_note: "₹1500–5000/person/day; inner line permit required"
  },

  // ── LADAKH / HIGH ALTITUDE ────────────────────────────────────────

  {
    id: "leh_ladakh",
    name: "Leh + Ladakh",
    state_country: "Ladakh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 3, Mumbai: 4, Bangalore: 4, Chennai: 4, Hyderabad: 4, Kolkata: 4, Pune: 4, Ahmedabad: 4 },
    experience_types: ["mountains", "adventure", "offbeat", "culture", "roadtrip", "trekking"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 2500, max_per_day: 10000 },
    duration: { min_days: 7, ideal_days: 10, max_days: 15 },
    best_months: [6, 7, 8, 9],
    avoid_months: [11, 12, 1, 2, 3, 4, 5],
    scores: { romance: 4, adventure: 5, culture: 4, party: 1, nature: 5, family_friendly: 1, spiritual: 4, offbeat: 5, food: 2, safety: 3, solo_friendly: 3 },
    tags: ["Pangong Lake", "Nubra Valley", "Khardung La", "Thiksey monastery", "Magnetic Hill", "camel safari", "stargazing", "river rafting"],
    why_go: "India's ultimate bucket list destination — Pangong's blue lake, sand dunes in Nubra, and the world's highest roads.",
    not_for: ["families with elderly/young kids", "altitude-sensitive travelers", "winter visits", "short trips"],
    budget_note: "₹2500–10000/person/day; fly Leh for acclimatization — don't drive directly from Delhi"
  },

  {
    id: "puri_konark",
    name: "Puri + Konark",
    state_country: "Odisha, India",
    international: false,
    visa_required: false,
    region: "East India",
    proximity_hours: { Delhi: 24, Mumbai: 26, Bangalore: 16, Chennai: 12, Hyderabad: 12, Kolkata: 6, Pune: 26, Ahmedabad: 28 },
    experience_types: ["spiritual", "beach", "heritage", "culture"],
    group_fit: ["family-elderly", "couple", "friends", "solo"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1000, max_per_day: 4000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 1, culture: 5, party: 1, nature: 3, family_friendly: 4, spiritual: 5, offbeat: 2, food: 4, safety: 5, solo_friendly: 4 },
    tags: ["Jagannath Temple", "Konark Sun Temple", "Puri Beach", "Rath Yatra", "Chilika Lake", "Odissi dance", "seafood"],
    why_go: "Jagannath Temple (one of Char Dham) + UNESCO Konark Sun Temple + Chilika Lake flamingos — an underrated cultural circuit.",
    not_for: ["party groups", "adventure seekers", "monsoon visits"],
    budget_note: "₹1000–4000/person/day"
  }

]; // end WEST_EAST_INDIA

if (typeof module !== 'undefined') module.exports = WEST_EAST_INDIA;
