// PART 1 — Domestic: North India (Himachal, Uttarakhand, Rajasthan, UP, MP)
// Budget tiers: tight=<₹1.5k/day, budget=₹1.5-3.5k/day, mid=₹3.5-8k/day, premium=₹8k+/day
// Scores: 1 (poor fit) → 5 (perfect fit)

const NORTH_INDIA = [

  {
    id: "manali",
    name: "Manali",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 14, Mumbai: 20, Bangalore: 22, Chennai: 24, Hyderabad: 22, Kolkata: 24, Pune: 20, Ahmedabad: 20 },
    experience_types: ["mountains", "snow", "adventure", "nature", "chill", "roadtrip"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 7000 },
    duration: { min_days: 4, ideal_days: 5, max_days: 7 },
    best_months: [1, 2, 5, 6, 9, 10],
    avoid_months: [7, 8],
    scores: { romance: 4, adventure: 4, culture: 2, party: 2, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 2, food: 3, safety: 4, solo_friendly: 3 },
    tags: ["Solang Valley", "Rohtang Pass", "snow activities", "Old Manali cafes", "Hadimba temple", "river rafting"],
    why_go: "Snow in winter/summer, Solang Valley activities, charming Old Manali — India's most accessible mountain escape.",
    not_for: ["party seekers", "beach lovers", "short weekend trips from South India"],
    budget_note: "₹1500–7000/person/day depending on season and stay"
  },

  {
    id: "shimla_kufri",
    name: "Shimla + Kufri",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 7, Mumbai: 18, Bangalore: 22, Chennai: 24, Hyderabad: 22, Kolkata: 22, Pune: 18, Ahmedabad: 16 },
    experience_types: ["mountains", "heritage", "snow", "chill", "family"],
    group_fit: ["couple", "family-kids", "family-elderly"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [1, 2, 3, 10, 11, 12],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 2, culture: 3, party: 1, nature: 4, family_friendly: 5, spiritual: 1, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Mall Road", "toy train", "Kufri snow", "Christ Church", "colonial architecture", "apple orchards"],
    why_go: "Colonial charm, toy train ride, Kufri snow activities. India's most family-friendly hill station from Delhi.",
    not_for: ["adventure seekers", "party groups", "solo backpackers"],
    budget_note: "₹1500–6000/person/day"
  },

  {
    id: "kasol_kheerganga",
    name: "Kasol + Kheerganga",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 10, Mumbai: 22, Bangalore: 26, Chennai: 28, Hyderabad: 24, Kolkata: 26, Pune: 22, Ahmedabad: 18 },
    experience_types: ["mountains", "trekking", "backpacker", "offbeat", "nature", "chill"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["tight", "budget"], min_per_day: 800, max_per_day: 2500 },
    duration: { min_days: 3, ideal_days: 4, max_days: 6 },
    best_months: [4, 5, 6, 9, 10],
    avoid_months: [1, 2, 7, 8],
    scores: { romance: 3, adventure: 4, culture: 2, party: 2, nature: 5, family_friendly: 1, spiritual: 2, offbeat: 5, food: 3, safety: 3, solo_friendly: 5 },
    tags: ["Parvati Valley", "Kheerganga hot springs", "backpacker cafes", "Israeli food", "camping", "night sky"],
    why_go: "India's backpacker paradise — Parvati Valley, the Kheerganga trek ending in hot springs, cheap cafes.",
    not_for: ["families with kids", "elderly", "luxury seekers"],
    budget_note: "₹800–2500/person/day, very budget friendly"
  },

  {
    id: "mcleod_ganj_dharamshala",
    name: "Mcleod Ganj + Dharamshala",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 12, Mumbai: 22, Bangalore: 26, Chennai: 28, Hyderabad: 24, Kolkata: 26, Pune: 22, Ahmedabad: 20 },
    experience_types: ["mountains", "culture", "spiritual", "backpacker", "chill", "offbeat"],
    group_fit: ["friends", "couple", "solo", "solo-female"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 800, max_per_day: 4000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 6 },
    best_months: [3, 4, 5, 9, 10, 11],
    avoid_months: [1, 2, 7, 8],
    scores: { romance: 3, adventure: 3, culture: 5, party: 1, nature: 4, family_friendly: 2, spiritual: 5, offbeat: 4, food: 4, safety: 5, solo_friendly: 5 },
    tags: ["Tibetan culture", "Dalai Lama temple", "Triund trek", "cafes", "yoga", "monastery", "cricket stadium"],
    why_go: "Little Lhasa of India — Tibetan culture, mountain cafes, Triund sunrise trek, perfect for solo travelers.",
    not_for: ["party groups", "families with young kids", "luxury seekers"],
    budget_note: "₹800–4000/person/day"
  },

  {
    id: "spiti_valley",
    name: "Spiti Valley",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 18, Mumbai: 24, Bangalore: 28, Chennai: 30, Hyderabad: 26, Kolkata: 28, Pune: 24, Ahmedabad: 22 },
    experience_types: ["mountains", "offbeat", "adventure", "nature", "roadtrip", "trekking"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 5000 },
    duration: { min_days: 6, ideal_days: 8, max_days: 12 },
    best_months: [6, 7, 8, 9, 10],
    avoid_months: [11, 12, 1, 2, 3, 4],
    scores: { romance: 4, adventure: 5, culture: 3, party: 1, nature: 5, family_friendly: 1, spiritual: 3, offbeat: 5, food: 2, safety: 3, solo_friendly: 3 },
    tags: ["Key Monastery", "Chandratal Lake", "moonscape", "Pin Valley", "Kaza", "highest villages", "stargazing"],
    why_go: "Otherworldly moonscapes, ancient monasteries, and a road trip unlike anything in India. Best Sep-Oct.",
    not_for: ["families", "elderly", "budget weekend trips", "those who don't like rough roads"],
    budget_note: "₹1500–5000/person/day; roads only open Jun-Oct"
  },

  {
    id: "bir_billing",
    name: "Bir Billing",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 10, Mumbai: 22, Bangalore: 26, Chennai: 28, Hyderabad: 24, Kolkata: 26, Pune: 22, Ahmedabad: 20 },
    experience_types: ["adventure", "mountains", "offbeat", "nature"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["tight", "budget"], min_per_day: 1000, max_per_day: 3000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [3, 4, 5, 9, 10, 11],
    avoid_months: [7, 8, 12, 1, 2],
    scores: { romance: 2, adventure: 5, culture: 2, party: 1, nature: 4, family_friendly: 1, spiritual: 1, offbeat: 4, food: 2, safety: 4, solo_friendly: 4 },
    tags: ["paragliding", "world's second highest paragliding site", "camping", "Tibetan colony", "mountain views"],
    why_go: "World-class paragliding site — Bir is the adventure capital of the Himalayas for those who want to fly.",
    not_for: ["families", "non-adventure travelers", "luxury seekers"],
    budget_note: "₹1000–3000/person/day; paragliding ₹2500–4000 extra"
  },

  {
    id: "chitkul",
    name: "Chitkul",
    state_country: "Himachal Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 16, Mumbai: 24, Bangalore: 28, Chennai: 30, Hyderabad: 28, Kolkata: 28, Pune: 24, Ahmedabad: 22 },
    experience_types: ["mountains", "offbeat", "nature", "chill"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1200, max_per_day: 4000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [5, 6, 9, 10],
    avoid_months: [11, 12, 1, 2, 3, 4, 7, 8],
    scores: { romance: 4, adventure: 3, culture: 2, party: 1, nature: 5, family_friendly: 1, spiritual: 2, offbeat: 5, food: 2, safety: 4, solo_friendly: 3 },
    tags: ["last Indian village", "Baspa river", "apple orchards", "Kinnaur", "remote", "camping"],
    why_go: "India's last village before Tibet. Stunning valley, crystal river, and the most offbeat road trip end point.",
    not_for: ["families with kids", "short trips", "those who prefer comfort"],
    budget_note: "₹1200–4000/person/day; limited accommodation"
  },

  {
    id: "harsil",
    name: "Harsil",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 12, Mumbai: 20, Bangalore: 26, Chennai: 28, Hyderabad: 24, Kolkata: 26, Pune: 20, Ahmedabad: 18 },
    experience_types: ["mountains", "nature", "offbeat", "chill"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 4000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [5, 6, 9, 10],
    avoid_months: [11, 12, 1, 2, 3, 7, 8],
    scores: { romance: 5, adventure: 2, culture: 1, party: 1, nature: 5, family_friendly: 2, spiritual: 2, offbeat: 5, food: 2, safety: 4, solo_friendly: 3 },
    tags: ["apple orchards", "Bhagirathi river", "deodar forests", "very offbeat", "peaceful", "near Gangotri"],
    why_go: "Uttarakhand's best kept secret — apple orchards, turquoise Bhagirathi river, no crowds whatsoever.",
    not_for: ["families with kids", "party groups", "those who need good connectivity"],
    budget_note: "₹1500–4000/person/day; limited accommodation book in advance"
  },

  {
    id: "rishikesh",
    name: "Rishikesh",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 5, Mumbai: 18, Bangalore: 24, Chennai: 26, Hyderabad: 22, Kolkata: 22, Pune: 18, Ahmedabad: 16 },
    experience_types: ["spiritual", "adventure", "chill", "nature", "backpacker"],
    group_fit: ["couple", "friends", "solo", "solo-female", "family-elderly"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 800, max_per_day: 5000 },
    duration: { min_days: 2, ideal_days: 4, max_days: 7 },
    best_months: [2, 3, 4, 9, 10, 11],
    avoid_months: [7, 8],
    scores: { romance: 3, adventure: 4, culture: 3, party: 1, nature: 4, family_friendly: 3, spiritual: 5, offbeat: 2, food: 3, safety: 5, solo_friendly: 5 },
    tags: ["Ganga aarti", "river rafting", "bungee jumping", "yoga ashrams", "Beatles Ashram", "Laxman Jhula", "camping"],
    why_go: "Yoga capital of the world — Ganga aarti at dusk, river rafting, bungee jumping, and ashram stays all in one place.",
    not_for: ["party seekers", "luxury beach lovers"],
    budget_note: "₹800–5000/person/day — works for backpackers and mid-range travelers"
  },

  {
    id: "haridwar",
    name: "Haridwar",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 4, Mumbai: 18, Bangalore: 24, Chennai: 26, Hyderabad: 22, Kolkata: 22, Pune: 18, Ahmedabad: 16 },
    experience_types: ["spiritual", "pilgrimage", "culture"],
    group_fit: ["family-elderly", "couple", "solo"],
    budget: { tiers: ["tight", "budget"], min_per_day: 600, max_per_day: 2500 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [1, 2, 3, 10, 11, 12],
    avoid_months: [],
    scores: { romance: 2, adventure: 1, culture: 4, party: 1, nature: 2, family_friendly: 3, spiritual: 5, offbeat: 1, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["Har Ki Pauri", "Ganga aarti", "ghats", "pilgrimage", "Maha Kumbh", "religious rituals"],
    why_go: "India's most sacred city on the Ganges — the Har Ki Pauri aarti at sunset is unmissable.",
    not_for: ["party seekers", "beach lovers", "adventure travelers", "long stays"],
    budget_note: "Very affordable, ₹600–2500/person/day"
  },

  {
    id: "mussoorie",
    name: "Mussoorie",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 6, Mumbai: 18, Bangalore: 24, Chennai: 26, Hyderabad: 22, Kolkata: 22, Pune: 18, Ahmedabad: 16 },
    experience_types: ["mountains", "chill", "family", "nature"],
    group_fit: ["couple", "family-kids", "family-elderly"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [3, 4, 5, 9, 10, 11],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 2, culture: 2, party: 1, nature: 4, family_friendly: 5, spiritual: 1, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Mall Road", "Kempty Falls", "cable car", "George Everest peak", "colonial buildings", "Doon Valley views"],
    why_go: "Queen of the Hills — beautiful Doon Valley views, Mall Road, and a colonial charm perfect for families.",
    not_for: ["adventure seekers", "party groups", "solo backpackers"],
    budget_note: "₹1500–6000/person/day"
  },

  {
    id: "nainital",
    name: "Nainital",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 6, Mumbai: 20, Bangalore: 26, Chennai: 28, Hyderabad: 24, Kolkata: 22, Pune: 20, Ahmedabad: 18 },
    experience_types: ["mountains", "chill", "family", "nature", "lake"],
    group_fit: ["couple", "family-kids", "family-elderly"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [3, 4, 5, 9, 10, 11],
    avoid_months: [7, 8],
    scores: { romance: 4, adventure: 2, culture: 2, party: 1, nature: 4, family_friendly: 5, spiritual: 1, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Naini Lake", "boating", "cable car", "Snow View", "Mall Road", "Corbett nearby"],
    why_go: "The lake city of Uttarakhand — boating on Naini Lake, cable car to Snow View, charming bazaars.",
    not_for: ["adventure seekers", "party groups"],
    budget_note: "₹1500–6000/person/day"
  },

  {
    id: "chopta_tungnath",
    name: "Chopta + Tungnath + Chandrashila",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 9, Mumbai: 20, Bangalore: 26, Chennai: 28, Hyderabad: 24, Kolkata: 24, Pune: 20, Ahmedabad: 18 },
    experience_types: ["trekking", "mountains", "offbeat", "spiritual", "nature"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["tight", "budget"], min_per_day: 1000, max_per_day: 3000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [4, 5, 6, 10, 11],
    avoid_months: [7, 8],
    scores: { romance: 4, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 1, spiritual: 3, offbeat: 5, food: 2, safety: 4, solo_friendly: 4 },
    tags: ["Tungnath temple", "Chandrashila summit", "meadows", "Kedarnath views", "mini Switzerland", "rhododendrons"],
    why_go: "India's most underrated trek — Chandrashila summit with 360° Himalayan views including Kedarnath and Chaukhamba.",
    not_for: ["families with kids", "elderly", "luxury seekers"],
    budget_note: "₹1000–3000/person/day, budget camping available"
  },

  {
    id: "kedarkantha",
    name: "Kedarkantha Trek",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 10, Mumbai: 22, Bangalore: 28, Chennai: 30, Hyderabad: 26, Kolkata: 26, Pune: 22, Ahmedabad: 20 },
    experience_types: ["trekking", "snow", "mountains", "adventure"],
    group_fit: ["friends", "solo", "couple"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 5000 },
    duration: { min_days: 4, ideal_days: 6, max_days: 7 },
    best_months: [12, 1, 2, 3, 4],
    avoid_months: [7, 8, 9],
    scores: { romance: 3, adventure: 5, culture: 1, party: 1, nature: 5, family_friendly: 1, spiritual: 1, offbeat: 3, food: 2, safety: 4, solo_friendly: 4 },
    tags: ["beginner winter trek", "snow covered summit", "Sankri base camp", "360 views", "pine forests"],
    why_go: "India's best beginner snow trek — a 3-day climb with snow throughout and jaw-dropping Himalayan views at the top.",
    not_for: ["families with kids", "elderly", "very short trips"],
    budget_note: "₹2000–5000/person/day including trek fees and camping"
  },

  {
    id: "valley_of_flowers",
    name: "Valley of Flowers + Hemkund Sahib",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 12, Mumbai: 24, Bangalore: 30, Chennai: 32, Hyderabad: 28, Kolkata: 28, Pune: 24, Ahmedabad: 22 },
    experience_types: ["trekking", "nature", "spiritual", "offbeat", "adventure"],
    group_fit: ["friends", "couple", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 4000 },
    duration: { min_days: 5, ideal_days: 7, max_days: 9 },
    best_months: [7, 8],
    avoid_months: [10, 11, 12, 1, 2, 3, 4, 5],
    scores: { romance: 4, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 1, spiritual: 4, offbeat: 4, food: 2, safety: 4, solo_friendly: 3 },
    tags: ["UNESCO World Heritage", "500+ flower species", "Hemkund Sahib Gurudwara", "Ghangaria", "alpine meadows"],
    why_go: "Only open July-August — a UNESCO valley carpeted with 500+ wildflower species. A once-in-a-lifetime Indian trek.",
    not_for: ["families with kids", "elderly", "those who can't do 7+ day trips", "winter travel"],
    budget_note: "₹1500–4000/person/day; only open July-August"
  },

  {
    id: "mukteshwar",
    name: "Mukteshwar",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 7, Mumbai: 20, Bangalore: 26, Chennai: 28, Hyderabad: 24, Kolkata: 22, Pune: 20, Ahmedabad: 18 },
    experience_types: ["mountains", "nature", "chill", "offbeat"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 7000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [3, 4, 5, 10, 11],
    avoid_months: [7, 8],
    scores: { romance: 5, adventure: 2, culture: 2, party: 1, nature: 5, family_friendly: 3, spiritual: 2, offbeat: 4, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["apple orchards", "Himalayan views", "Nanda Devi views", "Chauli Ki Jali", "boutique stays", "peaceful"],
    why_go: "Quieter than Nainital, stunning Nanda Devi views, boutique apple farm stays — an underrated couple escape.",
    not_for: ["party groups", "adventure seekers", "families with very young kids"],
    budget_note: "₹2000–7000/person/day including boutique stays"
  },

  {
    id: "jim_corbett",
    name: "Jim Corbett National Park",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 5, Mumbai: 20, Bangalore: 26, Chennai: 28, Hyderabad: 24, Kolkata: 22, Pune: 20, Ahmedabad: 18 },
    experience_types: ["wildlife", "nature", "adventure"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 15000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [11, 12, 1, 2, 3, 4, 5, 6],
    avoid_months: [7, 8, 9],
    scores: { romance: 3, adventure: 4, culture: 1, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 2, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["tiger safari", "elephant safari", "Dhikala zone", "jungle resort", "bird watching", "river Ramganga"],
    why_go: "India's oldest national park and one of the best places to spot tigers close to Delhi.",
    not_for: ["party groups", "beach lovers", "budget backpackers"],
    budget_note: "₹3000–15000/person/day; safari fees extra ₹1000–2500"
  },

  {
    id: "auli",
    name: "Auli",
    state_country: "Uttarakhand, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 10, Mumbai: 22, Bangalore: 28, Chennai: 30, Hyderabad: 26, Kolkata: 26, Pune: 22, Ahmedabad: 20 },
    experience_types: ["snow", "skiing", "mountains", "adventure", "nature"],
    group_fit: ["friends", "couple", "family-kids"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 10000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [1, 2, 3],
    avoid_months: [5, 6, 7, 8, 9, 10],
    scores: { romance: 3, adventure: 5, culture: 1, party: 1, nature: 5, family_friendly: 3, spiritual: 1, offbeat: 3, food: 2, safety: 4, solo_friendly: 3 },
    tags: ["skiing", "India's best ski resort", "Nanda Devi views", "ropeway", "snow activities", "Joshimath nearby"],
    why_go: "India's best skiing destination — Nanda Devi backdrop, well-maintained slopes, and great snow Jan-Mar.",
    not_for: ["non-winter trips", "families with elderly", "budget travelers"],
    budget_note: "₹3000–10000/person/day; ski rentals and lessons extra"
  },

  {
    id: "jaipur",
    name: "Jaipur",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 4, Mumbai: 14, Bangalore: 22, Chennai: 24, Hyderabad: 20, Kolkata: 22, Pune: 14, Ahmedabad: 8 },
    experience_types: ["heritage", "culture", "food", "shopping"],
    group_fit: ["couple", "friends", "family-kids", "family-elderly", "solo"],
    budget: { tiers: ["tight", "budget", "mid", "premium"], min_per_day: 1000, max_per_day: 10000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 3, adventure: 2, culture: 5, party: 2, nature: 2, family_friendly: 4, spiritual: 2, offbeat: 1, food: 5, safety: 4, solo_friendly: 4 },
    tags: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar", "bazaars", "pink city", "block printing", "dal baati churma"],
    why_go: "India's most iconic heritage city — palaces, forts, bazaars, and the best Rajasthani food all in one.",
    not_for: ["beach lovers", "monsoon trips", "summer heat seekers"],
    budget_note: "₹1000–10000/person/day — works for all budgets"
  },

  {
    id: "jodhpur",
    name: "Jodhpur",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 8, Mumbai: 10, Bangalore: 22, Chennai: 24, Hyderabad: 18, Kolkata: 24, Pune: 10, Ahmedabad: 6 },
    experience_types: ["heritage", "culture", "food", "offbeat"],
    group_fit: ["couple", "friends", "family-kids", "family-elderly", "solo"],
    budget: { tiers: ["tight", "budget", "mid", "premium"], min_per_day: 1000, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 2, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 4, adventure: 2, culture: 5, party: 1, nature: 2, family_friendly: 4, spiritual: 2, offbeat: 3, food: 4, safety: 4, solo_friendly: 4 },
    tags: ["Mehrangarh Fort", "blue city", "rooftop cafes", "Jaswant Thada", "Bishnoi village safari", "lassi"],
    why_go: "The Blue City — Mehrangarh Fort is India's most dramatic fort, rooftop cafes with fort views are unforgettable.",
    not_for: ["beach lovers", "monsoon trips"],
    budget_note: "₹1000–8000/person/day"
  },

  {
    id: "jaisalmer",
    name: "Jaisalmer",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 12, Mumbai: 14, Bangalore: 26, Chennai: 28, Hyderabad: 22, Kolkata: 28, Pune: 14, Ahmedabad: 8 },
    experience_types: ["heritage", "desert", "adventure", "culture", "offbeat"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 1500, max_per_day: 12000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 5, adventure: 4, culture: 4, party: 1, nature: 3, family_friendly: 4, spiritual: 2, offbeat: 4, food: 3, safety: 4, solo_friendly: 4 },
    tags: ["Thar Desert", "camel safari", "desert camping", "golden fort", "Sam Sand Dunes", "folk music under stars"],
    why_go: "Sleeping under stars in the Thar Desert after a camel safari — the most magical night in Rajasthan.",
    not_for: ["summer heat trips", "beach lovers"],
    budget_note: "₹1500–12000/person/day; luxury desert camps ₹8000+"
  },

  {
    id: "udaipur",
    name: "Udaipur",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 10, Mumbai: 8, Bangalore: 20, Chennai: 22, Hyderabad: 16, Kolkata: 24, Pune: 8, Ahmedabad: 4 },
    experience_types: ["heritage", "romance", "culture", "food", "lake"],
    group_fit: ["couple", "family-elderly", "solo", "friends"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 1500, max_per_day: 15000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 5, adventure: 1, culture: 5, party: 1, nature: 3, family_friendly: 4, spiritual: 2, offbeat: 2, food: 5, safety: 5, solo_friendly: 4 },
    tags: ["City Palace", "Lake Pichola", "boat ride", "Jag Mandir", "rooftop restaurants", "Lake Palace hotel"],
    why_go: "India's most romantic city — lake palaces, candlelit rooftop restaurants, and the City Palace at sunset.",
    not_for: ["adventure seekers", "party groups", "beach lovers"],
    budget_note: "₹1500–15000/person/day; lake-facing heritage hotels worth the splurge"
  },

  {
    id: "pushkar",
    name: "Pushkar",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 7, Mumbai: 14, Bangalore: 24, Chennai: 26, Hyderabad: 20, Kolkata: 26, Pune: 14, Ahmedabad: 8 },
    experience_types: ["spiritual", "culture", "offbeat", "backpacker", "chill"],
    group_fit: ["couple", "friends", "solo", "solo-female"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 800, max_per_day: 4000 },
    duration: { min_days: 2, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 3, adventure: 2, culture: 5, party: 1, nature: 2, family_friendly: 2, spiritual: 5, offbeat: 3, food: 3, safety: 4, solo_friendly: 5 },
    tags: ["Brahma temple", "sacred lake", "camel fair", "ghats", "rooftop cafes", "backpacker town", "Holi celebrations"],
    why_go: "India's only Brahma temple, sacred lake, and the world's largest camel fair (November). A spiritual backpacker town.",
    not_for: ["party groups", "beach lovers", "long stays"],
    budget_note: "₹800–4000/person/day, very budget friendly"
  },

  {
    id: "ranthambore",
    name: "Ranthambore National Park",
    state_country: "Rajasthan, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 5, Mumbai: 14, Bangalore: 24, Chennai: 26, Hyderabad: 20, Kolkata: 24, Pune: 14, Ahmedabad: 8 },
    experience_types: ["wildlife", "nature", "adventure"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3500, max_per_day: 15000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5, 6],
    avoid_months: [7, 8, 9],
    scores: { romance: 3, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 2, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["tiger sightings", "highest density tigers", "jeep safari", "canter safari", "ancient fort", "Rajbagh lake"],
    why_go: "India's best tiger sighting probability — Ranthambore has the highest tiger density, just 5hr from Delhi.",
    not_for: ["party groups", "budget backpackers", "beach lovers"],
    budget_note: "₹3500–15000/person/day; safari ₹1200–2500 extra per ride"
  },

  {
    id: "agra",
    name: "Agra",
    state_country: "Uttar Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 3, Mumbai: 16, Bangalore: 24, Chennai: 26, Hyderabad: 20, Kolkata: 22, Pune: 16, Ahmedabad: 12 },
    experience_types: ["heritage", "culture", "history"],
    group_fit: ["couple", "family-kids", "family-elderly", "solo"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1000, max_per_day: 5000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 4, adventure: 1, culture: 5, party: 1, nature: 1, family_friendly: 4, spiritual: 2, offbeat: 1, food: 3, safety: 4, solo_friendly: 4 },
    tags: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh", "petha", "sunrise Taj"],
    why_go: "Taj Mahal at sunrise is worth the trip alone. Often combined with Jaipur and Delhi for the Golden Triangle.",
    not_for: ["long stays", "beach lovers", "party groups", "summer travel"],
    budget_note: "₹1000–5000/person/day; Taj entry ₹1100 for Indians"
  },

  {
    id: "varanasi",
    name: "Varanasi",
    state_country: "Uttar Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 8, Mumbai: 18, Bangalore: 26, Chennai: 28, Hyderabad: 22, Kolkata: 12, Pune: 18, Ahmedabad: 18 },
    experience_types: ["spiritual", "pilgrimage", "culture", "offbeat"],
    group_fit: ["couple", "family-elderly", "solo", "solo-female", "friends"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 800, max_per_day: 4000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 2, adventure: 2, culture: 5, party: 1, nature: 1, family_friendly: 3, spiritual: 5, offbeat: 3, food: 4, safety: 4, solo_friendly: 5 },
    tags: ["Ganga ghats", "morning boat ride", "aarti", "Kashi Vishwanath", "Dev Deepawali", "lassi", "silk sarees"],
    why_go: "India's most ancient city — boat ride at dawn on the Ganges, Ganga aarti at night, Kashi Vishwanath temple.",
    not_for: ["beach lovers", "adventure seekers", "party groups"],
    budget_note: "₹800–4000/person/day; very affordable"
  },

  {
    id: "mathura_vrindavan",
    name: "Mathura + Vrindavan",
    state_country: "Uttar Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 2, Mumbai: 16, Bangalore: 24, Chennai: 26, Hyderabad: 20, Kolkata: 22, Pune: 16, Ahmedabad: 12 },
    experience_types: ["spiritual", "pilgrimage", "culture"],
    group_fit: ["family-elderly", "couple", "solo"],
    budget: { tiers: ["tight", "budget"], min_per_day: 600, max_per_day: 2500 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 2, adventure: 1, culture: 4, party: 1, nature: 1, family_friendly: 3, spiritual: 5, offbeat: 1, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["birthplace of Krishna", "Banke Bihari temple", "Prem Mandir", "Holi celebrations", "Lathmar Holi", "ghats"],
    why_go: "Birthplace of Lord Krishna — the most vibrant Holi celebrations in India happen in Mathura and Barsana.",
    not_for: ["non-religious travelers on leisure trips", "long stays", "beach lovers"],
    budget_note: "₹600–2500/person/day; very affordable"
  },

  {
    id: "gwalior",
    name: "Gwalior",
    state_country: "Madhya Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 4, Mumbai: 14, Bangalore: 24, Chennai: 26, Hyderabad: 18, Kolkata: 20, Pune: 14, Ahmedabad: 12 },
    experience_types: ["heritage", "history", "culture"],
    group_fit: ["couple", "family-kids", "family-elderly", "solo", "friends"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 800, max_per_day: 4000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 3, adventure: 1, culture: 5, party: 1, nature: 2, family_friendly: 4, spiritual: 2, offbeat: 3, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["Gwalior Fort", "Man Singh Palace", "Sas Bahu temple", "Tansen music festival", "Jai Vilas Palace"],
    why_go: "One of India's most impressive forts — Gwalior Fort's Man Singh Palace rivals anything in Rajasthan, far fewer tourists.",
    not_for: ["beach lovers", "party groups", "long stays"],
    budget_note: "₹800–4000/person/day; very underrated"
  },

  {
    id: "khajuraho",
    name: "Khajuraho",
    state_country: "Madhya Pradesh, India",
    international: false,
    visa_required: false,
    region: "North India",
    proximity_hours: { Delhi: 8, Mumbai: 18, Bangalore: 26, Chennai: 28, Hyderabad: 22, Kolkata: 20, Pune: 18, Ahmedabad: 16 },
    experience_types: ["heritage", "culture", "offbeat"],
    group_fit: ["couple", "solo", "friends"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1000, max_per_day: 4000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 3, adventure: 1, culture: 5, party: 1, nature: 2, family_friendly: 2, spiritual: 3, offbeat: 4, food: 2, safety: 5, solo_friendly: 4 },
    tags: ["UNESCO World Heritage", "erotic temples", "Chandela dynasty", "light and sound show", "tribal art"],
    why_go: "UNESCO Heritage temples with extraordinary medieval sculpture — India's most unique heritage site.",
    not_for: ["families with very young kids", "beach lovers", "long stays"],
    budget_note: "₹1000–4000/person/day"
  }

]; // end NORTH_INDIA

if (typeof module !== 'undefined') module.exports = NORTH_INDIA;
