// PART 2 — Domestic: South India (Karnataka, Kerala, Tamil Nadu, Andhra, Telangana)

const SOUTH_INDIA = [

  {
    id: "coorg",
    name: "Coorg",
    state_country: "Karnataka, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 26, Mumbai: 14, Bangalore: 4, Chennai: 8, Hyderabad: 9, Kolkata: 28, Pune: 14, Ahmedabad: 18 },
    experience_types: ["mountains", "nature", "chill", "wildlife", "offbeat"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 2, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 2, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["coffee estates", "Abbey Falls", "Dubare elephant camp", "mist", "Bhagamandala", "Raja's Seat", "forest resorts"],
    why_go: "Misty coffee estates, Abbey Falls, and forest resorts — South India's most romantic hill escape.",
    not_for: ["party groups", "beach lovers"],
    budget_note: "₹2000–8000/person/day"
  },

  {
    id: "hampi",
    name: "Hampi",
    state_country: "Karnataka, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 28, Mumbai: 10, Bangalore: 6, Chennai: 8, Hyderabad: 6, Kolkata: 30, Pune: 10, Ahmedabad: 14 },
    experience_types: ["heritage", "offbeat", "backpacker", "culture", "nature"],
    group_fit: ["friends", "couple", "solo", "solo-female"],
    budget: { tiers: ["tight", "budget"], min_per_day: 800, max_per_day: 2500 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [4, 5, 6, 7, 8],
    scores: { romance: 3, adventure: 2, culture: 5, party: 1, nature: 4, family_friendly: 2, spiritual: 3, offbeat: 5, food: 3, safety: 4, solo_friendly: 5 },
    tags: ["Vijayanagara ruins", "UNESCO Heritage", "boulders", "Virupaksha temple", "coracle ride", "cycling", "Hippie Island"],
    why_go: "Surreal boulder landscape with 14th-century Vijayanagara ruins — India's most unique backpacker heritage destination.",
    not_for: ["families with young kids", "luxury seekers", "very short trips"],
    budget_note: "₹800–2500/person/day; very budget friendly"
  },

  {
    id: "chikmagalur",
    name: "Chikmagalur",
    state_country: "Karnataka, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 28, Mumbai: 14, Bangalore: 5, Chennai: 9, Hyderabad: 10, Kolkata: 32, Pune: 14, Ahmedabad: 20 },
    experience_types: ["mountains", "nature", "chill", "offbeat", "trekking"],
    group_fit: ["couple", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 3, culture: 1, party: 1, nature: 5, family_friendly: 3, spiritual: 1, offbeat: 3, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["coffee estates", "Mullayanagiri peak", "Baba Budangiri", "waterfalls", "trekking", "mist"],
    why_go: "Karnataka's highest peak + coffee estates + misty mornings — quieter and greener than Coorg.",
    not_for: ["party groups", "beach lovers", "families with very young kids"],
    budget_note: "₹1500–6000/person/day"
  },

  {
    id: "kabini_nagarhole",
    name: "Kabini + Nagarhole",
    state_country: "Karnataka, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 28, Mumbai: 14, Bangalore: 4, Chennai: 8, Hyderabad: 9, Kolkata: 32, Pune: 14, Ahmedabad: 20 },
    experience_types: ["wildlife", "nature", "adventure"],
    group_fit: ["couple", "friends", "family-kids"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 15000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 3, adventure: 4, culture: 1, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 3, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["elephant sightings", "tiger sightings", "leopard", "boat safari", "jeep safari", "Kabini backwaters"],
    why_go: "South India's best wildlife destination — very high elephant and leopard sighting rates, stunning Kabini river setting.",
    not_for: ["party groups", "beach lovers", "budget backpackers"],
    budget_note: "₹3000–15000/person/day; forest dept safaris affordable at ₹600–1200"
  },

  {
    id: "gokarna",
    name: "Gokarna",
    state_country: "Karnataka, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 30, Mumbai: 10, Bangalore: 7, Chennai: 12, Hyderabad: 11, Kolkata: 34, Pune: 10, Ahmedabad: 16 },
    experience_types: ["beach", "spiritual", "backpacker", "chill", "offbeat"],
    group_fit: ["friends", "couple", "solo", "solo-female"],
    budget: { tiers: ["tight", "budget"], min_per_day: 800, max_per_day: 3000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 2, culture: 3, party: 2, nature: 4, family_friendly: 2, spiritual: 4, offbeat: 4, food: 3, safety: 4, solo_friendly: 5 },
    tags: ["Om Beach", "Half Moon Beach", "Paradise Beach", "Mahabaleshwar temple", "cliff jumping", "backpacker haven"],
    why_go: "Goa before it got crowded — beautiful secluded beaches, a sacred Shiva temple, and a real backpacker vibe.",
    not_for: ["families with young kids", "luxury seekers", "party seekers"],
    budget_note: "₹800–3000/person/day"
  },

  {
    id: "munnar",
    name: "Munnar",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 30, Mumbai: 16, Bangalore: 7, Chennai: 8, Hyderabad: 12, Kolkata: 34, Pune: 16, Ahmedabad: 22 },
    experience_types: ["mountains", "nature", "chill", "tea estates"],
    group_fit: ["couple", "family-kids", "friends", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4],
    avoid_months: [6, 7, 8],
    scores: { romance: 5, adventure: 2, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 2, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["tea plantations", "Eravikulam National Park", "Nilgiri Tahr", "Mattupetty dam", "Echo Point", "Neelakurinji"],
    why_go: "Endless rolling tea gardens at 1600m — Kerala's most scenic hill station with cool weather even in summer.",
    not_for: ["beach lovers", "party groups", "monsoon visits"],
    budget_note: "₹2000–8000/person/day"
  },

  {
    id: "alleppey_kumarakom",
    name: "Alleppey + Kumarakom (Backwaters)",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 32, Mumbai: 16, Bangalore: 8, Chennai: 8, Hyderabad: 13, Kolkata: 36, Pune: 16, Ahmedabad: 22 },
    experience_types: ["nature", "chill", "culture", "houseboat"],
    group_fit: ["couple", "family-elderly", "friends"],
    budget: { tiers: ["budget", "mid", "premium"], min_per_day: 2500, max_per_day: 12000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 5, adventure: 1, culture: 3, party: 1, nature: 5, family_friendly: 3, spiritual: 1, offbeat: 2, food: 5, safety: 5, solo_friendly: 2 },
    tags: ["houseboat", "backwaters", "Chinese fishing nets", "coconut lagoons", "toddy", "Kerala cuisine", "sunset cruises"],
    why_go: "Overnight in a private houseboat drifting through palm-lined backwaters — India's most romantic water experience.",
    not_for: ["solo travelers", "adventure seekers", "party groups", "very budget trips"],
    budget_note: "₹2500–12000/person/day; houseboat night ₹6000–20000 for the boat"
  },

  {
    id: "wayanad",
    name: "Wayanad",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 30, Mumbai: 16, Bangalore: 5, Chennai: 9, Hyderabad: 11, Kolkata: 34, Pune: 16, Ahmedabad: 22 },
    experience_types: ["nature", "mountains", "wildlife", "offbeat", "trekking"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 3, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 4, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["Banasura Sagar Dam", "Chembra Peak", "tribal culture", "coffee estates", "Edakkal Caves", "bamboo forests"],
    why_go: "Quieter and more offbeat than Coorg — tribal culture, bamboo forests, and the beautiful Chembra Peak trek.",
    not_for: ["party groups", "beach lovers"],
    budget_note: "₹1500–6000/person/day"
  },

  {
    id: "varkala",
    name: "Varkala",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 32, Mumbai: 16, Bangalore: 6, Chennai: 7, Hyderabad: 12, Kolkata: 36, Pune: 16, Ahmedabad: 22 },
    experience_types: ["beach", "chill", "spiritual", "backpacker", "offbeat"],
    group_fit: ["couple", "friends", "solo", "solo-female"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1000, max_per_day: 5000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 4, adventure: 2, culture: 3, party: 2, nature: 4, family_friendly: 2, spiritual: 3, offbeat: 4, food: 4, safety: 5, solo_friendly: 5 },
    tags: ["clifftop restaurants", "Papanasam Beach", "cliff walks", "sunset", "yoga", "Janardhana temple", "Ayurveda"],
    why_go: "Dramatic red cliffs above the Arabian Sea, excellent seafood, and a relaxed hippie vibe — Kerala's coolest beach.",
    not_for: ["families with young kids", "party groups", "rough sea during monsoon"],
    budget_note: "₹1000–5000/person/day"
  },

  {
    id: "fort_kochi",
    name: "Fort Kochi + Cochin",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 30, Mumbai: 14, Bangalore: 7, Chennai: 7, Hyderabad: 12, Kolkata: 34, Pune: 14, Ahmedabad: 20 },
    experience_types: ["culture", "heritage", "food", "chill", "offbeat"],
    group_fit: ["couple", "friends", "solo", "solo-female", "family-elderly"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 4, adventure: 1, culture: 5, party: 2, nature: 2, family_friendly: 4, spiritual: 2, offbeat: 3, food: 5, safety: 5, solo_friendly: 5 },
    tags: ["Chinese fishing nets", "Dutch Palace", "Jew Town", "street art", "Kerala cuisine", "ferry rides", "antiques"],
    why_go: "India's most charming port town — Dutch, Portuguese, Jewish, and Chinese influences in one walkable historic quarter.",
    not_for: ["adventure seekers", "beach lovers", "long stays beyond 2-3 days"],
    budget_note: "₹1500–6000/person/day"
  },

  {
    id: "thekkady_periyar",
    name: "Thekkady + Periyar",
    state_country: "Kerala, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 30, Mumbai: 16, Bangalore: 8, Chennai: 8, Hyderabad: 13, Kolkata: 34, Pune: 16, Ahmedabad: 22 },
    experience_types: ["wildlife", "nature", "trekking", "spices"],
    group_fit: ["couple", "family-kids", "friends"],
    budget: { tiers: ["budget", "mid"], min_per_day: 2000, max_per_day: 8000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3, 4],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 3, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 2, food: 4, safety: 5, solo_friendly: 3 },
    tags: ["Periyar Lake boat ride", "elephant spotting", "spice plantations", "bamboo rafting", "Kathakali", "tribal treks"],
    why_go: "Boat safari on Periyar Lake spotting elephants + visiting spice plantations + Kathakali performance at night.",
    not_for: ["beach lovers", "party groups"],
    budget_note: "₹2000–8000/person/day"
  },

  {
    id: "pondicherry",
    name: "Pondicherry",
    state_country: "Puducherry, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 28, Mumbai: 18, Bangalore: 4, Chennai: 2, Hyderabad: 10, Kolkata: 32, Pune: 18, Ahmedabad: 24 },
    experience_types: ["beach", "culture", "chill", "food", "heritage", "spiritual"],
    group_fit: ["couple", "friends", "solo", "solo-female", "family-elderly"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 2, ideal_days: 3, max_days: 4 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [11],
    scores: { romance: 4, adventure: 1, culture: 5, party: 2, nature: 3, family_friendly: 4, spiritual: 3, offbeat: 3, food: 5, safety: 5, solo_friendly: 5 },
    tags: ["French Quarter", "Auroville", "promenade", "cafes", "Sri Aurobindo Ashram", "Serenity Beach", "Tamil cuisine"],
    why_go: "India's only French colonial town — yellow buildings, great cafes, Auroville, a peaceful promenade and good beach.",
    not_for: ["party groups", "adventure seekers", "monsoon visits"],
    budget_note: "₹1500–6000/person/day"
  },

  {
    id: "ooty_kodaikanal",
    name: "Ooty + Kodaikanal",
    state_country: "Tamil Nadu, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 30, Mumbai: 16, Bangalore: 5, Chennai: 6, Hyderabad: 11, Kolkata: 34, Pune: 16, Ahmedabad: 22 },
    experience_types: ["mountains", "nature", "chill", "family"],
    group_fit: ["family-kids", "couple", "family-elderly"],
    budget: { tiers: ["budget", "mid"], min_per_day: 1500, max_per_day: 6000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 6 },
    best_months: [3, 4, 5, 10, 11, 12],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 2, culture: 2, party: 1, nature: 4, family_friendly: 5, spiritual: 1, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["toy train", "Doddabetta peak", "rose garden", "Kodaikanal Lake", "Coaker's Walk", "pine forests", "chocolates"],
    why_go: "Tamil Nadu's classic hill station combo — Ooty's toy train + Kodaikanal's pine-ringed lake. Perfect family circuit.",
    not_for: ["party groups", "adventure seekers", "solo backpackers"],
    budget_note: "₹1500–6000/person/day"
  },

  {
    id: "madurai",
    name: "Madurai",
    state_country: "Tamil Nadu, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 30, Mumbai: 18, Bangalore: 7, Chennai: 6, Hyderabad: 13, Kolkata: 34, Pune: 18, Ahmedabad: 24 },
    experience_types: ["spiritual", "pilgrimage", "heritage", "culture", "food"],
    group_fit: ["family-elderly", "couple", "solo", "friends"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1000, max_per_day: 4000 },
    duration: { min_days: 2, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 2, adventure: 1, culture: 5, party: 1, nature: 1, family_friendly: 4, spiritual: 5, offbeat: 2, food: 5, safety: 5, solo_friendly: 4 },
    tags: ["Meenakshi Amman temple", "night temple visit", "Thirumalai Nayak Palace", "idli", "chettinad food", "Jallikattu"],
    why_go: "Meenakshi Amman temple is one of India's most magnificent — the night puja is extraordinary. Great South Indian food.",
    not_for: ["beach lovers", "adventure seekers", "long stays"],
    budget_note: "₹1000–4000/person/day"
  },

  {
    id: "rameswaram",
    name: "Rameswaram",
    state_country: "Tamil Nadu, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 32, Mumbai: 20, Bangalore: 9, Chennai: 7, Hyderabad: 15, Kolkata: 36, Pune: 20, Ahmedabad: 26 },
    experience_types: ["spiritual", "pilgrimage", "beach", "culture"],
    group_fit: ["family-elderly", "couple", "solo"],
    budget: { tiers: ["tight", "budget"], min_per_day: 800, max_per_day: 3000 },
    duration: { min_days: 2, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [5, 6, 7, 8],
    scores: { romance: 2, adventure: 1, culture: 4, party: 1, nature: 3, family_friendly: 3, spiritual: 5, offbeat: 3, food: 3, safety: 5, solo_friendly: 4 },
    tags: ["Ramanathaswamy temple", "Pamban Bridge", "Adam's Bridge", "Dhanushkodi ghost town", "22 holy wells"],
    why_go: "One of India's holiest Hindu temples + Dhanushkodi's abandoned ghost town — a deeply unique spiritual journey.",
    not_for: ["beach party seekers", "adventure seekers", "long stays"],
    budget_note: "₹800–3000/person/day"
  },

  {
    id: "mahabalipuram",
    name: "Mahabalipuram",
    state_country: "Tamil Nadu, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 28, Mumbai: 18, Bangalore: 4, Chennai: 1, Hyderabad: 10, Kolkata: 32, Pune: 18, Ahmedabad: 24 },
    experience_types: ["heritage", "beach", "culture", "offbeat"],
    group_fit: ["couple", "friends", "solo", "family-kids"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1000, max_per_day: 4000 },
    duration: { min_days: 1, ideal_days: 2, max_days: 3 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [11],
    scores: { romance: 3, adventure: 1, culture: 5, party: 1, nature: 3, family_friendly: 4, spiritual: 3, offbeat: 3, food: 4, safety: 5, solo_friendly: 4 },
    tags: ["Shore Temple", "Arjuna's Penance", "Five Rathas", "UNESCO Heritage", "beach", "seafood", "stone carving"],
    why_go: "UNESCO World Heritage rock-cut temples on the Bay of Bengal — the Shore Temple at dawn is breathtaking.",
    not_for: ["long stays", "party groups", "adventure seekers"],
    budget_note: "₹1000–4000/person/day; often a day trip from Chennai"
  },

  {
    id: "vizag_araku",
    name: "Vizag + Araku Valley",
    state_country: "Andhra Pradesh, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 28, Mumbai: 18, Bangalore: 9, Chennai: 8, Hyderabad: 7, Kolkata: 18, Pune: 18, Ahmedabad: 24 },
    experience_types: ["beach", "mountains", "nature", "offbeat", "chill"],
    group_fit: ["couple", "family-kids", "friends"],
    budget: { tiers: ["tight", "budget", "mid"], min_per_day: 1200, max_per_day: 4000 },
    duration: { min_days: 3, ideal_days: 4, max_days: 5 },
    best_months: [10, 11, 12, 1, 2, 3],
    avoid_months: [6, 7, 8],
    scores: { romance: 3, adventure: 2, culture: 2, party: 2, nature: 4, family_friendly: 4, spiritual: 1, offbeat: 4, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["RK Beach", "Araku Valley coffee", "Borra Caves", "tribal villages", "toy train", "INS Kurusura submarine museum"],
    why_go: "Vizag's beaches + Araku Valley's tribal coffee and toy train combo — South India's most underrated destination.",
    not_for: ["party groups", "luxury beach seekers"],
    budget_note: "₹1200–4000/person/day"
  },

  {
    id: "tirupati",
    name: "Tirupati + Tirumala",
    state_country: "Andhra Pradesh, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 28, Mumbai: 16, Bangalore: 4, Chennai: 3, Hyderabad: 8, Kolkata: 30, Pune: 16, Ahmedabad: 22 },
    experience_types: ["spiritual", "pilgrimage"],
    group_fit: ["family-elderly", "solo", "couple"],
    budget: { tiers: ["tight", "budget"], min_per_day: 600, max_per_day: 2500 },
    duration: { min_days: 1, ideal_days: 2, max_days: 2 },
    best_months: [1, 2, 3, 10, 11, 12],
    avoid_months: [],
    scores: { romance: 1, adventure: 1, culture: 3, party: 1, nature: 2, family_friendly: 4, spiritual: 5, offbeat: 1, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Venkateswara temple", "richest temple in world", "prasadam ladoo", "hair tonsuring", "Govindabhoga"],
    why_go: "The Venkateswara temple is India's most visited and richest — a deeply powerful pilgrimage for Hindu devotees.",
    not_for: ["non-religious travelers", "adventure seekers", "beach lovers"],
    budget_note: "₹600–2500/person/day; very affordable including temple stay options"
  },

  {
    id: "andaman",
    name: "Andaman & Nicobar Islands",
    state_country: "Andaman & Nicobar, India",
    international: false,
    visa_required: false,
    region: "South India",
    proximity_hours: { Delhi: 3, Mumbai: 3, Bangalore: 2, Chennai: 2, Hyderabad: 3, Kolkata: 2, Pune: 3, Ahmedabad: 3 },
    experience_types: ["beach", "nature", "adventure", "scuba diving", "island"],
    group_fit: ["couple", "friends", "family-kids", "solo"],
    budget: { tiers: ["mid", "premium"], min_per_day: 3000, max_per_day: 12000 },
    duration: { min_days: 5, ideal_days: 7, max_days: 10 },
    best_months: [10, 11, 12, 1, 2, 3, 4, 5],
    avoid_months: [6, 7, 8, 9],
    scores: { romance: 5, adventure: 4, culture: 2, party: 1, nature: 5, family_friendly: 4, spiritual: 1, offbeat: 3, food: 3, safety: 5, solo_friendly: 3 },
    tags: ["Radhanagar Beach", "Havelock Island", "Neil Island", "scuba diving", "glass bottom boat", "Cellular Jail", "turquoise water"],
    why_go: "Asia's best beach (Radhanagar), crystal turquoise water, world-class scuba — India's Maldives without the visa.",
    not_for: ["monsoon visits", "very budget travelers", "short weekend trips"],
    budget_note: "₹3000–12000/person/day; flights add ₹6000–15000 per person"
  }

]; // end SOUTH_INDIA

if (typeof module !== 'undefined') module.exports = SOUTH_INDIA;
